### ISSUE TITLE
Crash when clicking "Preview" on Create World menu

### ISSUE THREAD

**Issue by coegho** [MovingBlocks/Terasology#1529] opened 2015-01-16 11:08 UTC
org.reflections.ReflectionsException: could not get type for name org.terasology.was.generator.plant.forest.tree.BroomForestSpawnDefinition
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:378)
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:387)
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:351)
	at org.terasology.module.ModuleEnvironment.getTypesAnnotatedWith(ModuleEnvironment.java:279)
	at org.terasology.world.generator.plugin.DefaultWorldGeneratorPluginLibrary.<init>(DefaultWorldGeneratorPluginLibrary.java:39)
	at org.terasology.world.generator.plugin.TempWorldGeneratorPluginLibrary.<init>(TempWorldGeneratorPluginLibrary.java:40)
	at org.terasology.rendering.nui.layers.mainMenu.PreviewWorldScreen.onOpened(PreviewWorldScreen.java:94)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:639)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:285)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:249)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:236)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:267)
	at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen$10.onActivated(CreateGameScreen.java:297)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138)
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:226)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:558)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:166)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:393)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:248)
	at org.terasology.input.InputSystem.update(InputSystem.java:204)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:139)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:442)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:356)
	at org.terasology.engine.Terasology.main(Terasology.java:117)

**Comment by msteiger** [comment] 2015-01-16 11:52
Thanks for reporting this. It seems to be a duplicate of #1524.

**Closed by msteiger** 2015-01-16 11:52 UTC
