### ISSUE TITLE
Sort entries in the language dropdown under player settings

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2350] opened 2016-06-09 23:42 UTC
Just merged a PR that does much the same for the launcher, realized we need it here too.

https://github.com/MovingBlocks/TerasologyLauncher/pull/369

Maybe of interest to @mtjvankuik who did the launcher version :-)

**Comment by mtjvankuik** [comment] 2016-06-10 20:00
I have made a PR in which the issue is fixed.

**Comment by Cervator** [comment] 2016-06-10 20:55
@mtjvankuik cool but to where? :-) I don't see it under PRs in this repo

**Comment by mtjvankuik** [comment] 2016-06-10 21:04
It took a bit longer than expected, due to some files that were committed which should not be committed. In 2 minutes i have made the PR :')

**Closed** 2016-06-10 22:26 UTC
Labels: Bite-size, UI
