### ISSUE TITLE
Layout overlapping!

### ISSUE THREAD

**Issue by SurajDatta** [MovingBlocks/Terasology#3182] opened 2017-12-15 18:39 UTC
### What you were trying to do
Resizing My game's window and checking if it was compatible with the original game window size.

### What actually happened
The start bar (where we select the game's name) was overlapping with the continue button. 

### How to reproduce

* Step 1: Open the game
* Step 2: If the game window is not full-sized, leave it as it is. if not bring it to its default size.
* Step 3: press single player and the create a new game, then the screen which comes, the buttons should be overlapped.

### Log details and game version
the newest version in the Terasology git.

### Computer details
![screenshot 154 _li](https://user-images.githubusercontent.com/34120444/34055479-c4999bb6-e1e8-11e7-98f6-28eec6ef9f28.jpg)

I also have attached an image of the bug for your reference!
![screenshot 151](https://user-images.githubusercontent.com/34120444/34055422-8c83605e-e1e8-11e7-8216-e880663d4cdd.png)

**Comment by vampcat** [comment] 2017-12-16 03:42
Hey Suraj, good to see you sticking around :)

A quick issue search on github brought this up: https://github.com/MovingBlocks/Terasology/issues/2716
As you can see, the problem is already pretty well documented. However, no real solution has been proposed as of yet - if you can suggest some way to take care of this, we'll be happy to approve the task :D

**Comment by SurajDatta** [comment] 2017-12-16 12:43
Hi, vampcat, Sorry for this, I did not realize that it was already posted. I am not sure how to code it but I can give suggestions on how to solve this matter. Hope it helps!

**Comment by SurajDatta** [comment] 2017-12-16 12:58
First, let us find the ratio of the button to the screen resolution, and then, when the user resizes the screen the buttons will also resize with it until the perimeter of the button reaches/touches the letters. If so, then we will either 1. move the button to a random direction (Keeping in mind that the "Play" button should not cross the imaginary middle line of the screen and should not overlap any of the boxes highlighted greyish color. the same goes for "Back" button)

2) If the game identifies an overlapping box, it can either move a certain direction up/down/right/left depending on other boxes.  In this case, it is going to be better if the "play" moves left and "back" moves right (just like how you organize am IOS folder).

I am not fully sure if it is going to work or not. But hope it help!

**Comment by SurajDatta** [comment] 2017-12-16 16:34
hi, is it that we have to remove the game's path from create game screen?

**Comment by SurajDatta** [comment] 2017-12-16 17:14
So the answer to @vampcat 's problem is Scrolling! (or what I like to call unwrapping ;) )
Thanks, @jellysnake and @vampcat !

**Comment by jellysnake** [comment] 2018-01-29 07:55
Closing this as it's covered in #2716 and adding a note there to check discussion on this issue.

**Closed by jellysnake** 2018-01-29 07:55 UTC
Labels: UI
