### ISSUE TITLE
Advanced Game Setup: "Disable All" actually disables all, including active gameplay module

### ISSUE THREAD

**Issue by Qwertygiy** [MovingBlocks/Terasology#4129] opened 2020-08-17 19:29 UTC
### What you were trying to do
Disable all manually-selected modules so that only the default selection for the gameplay template are used.

### What actually happened
*All* modules are disabled, including the active module, which cannot be enabled or disabled from the UI.

### How to reproduce

* 1) Ensure that you have multiple gameplay templates available, such as Terasology/GooeysQuests or Terasology/JoshariasSurvival
* 2) Select one of these templates and go to Advanced Setup
* 3) Select Disable All
* 4) Optionally, attempt to start game to ensure that it is not merely a UI error. Only the "engine" module will activate -- resulting in a failure to start, due to lack of a rendering module.

**Comment by DarkWeird** [comment] 2020-08-31 07:50
What is expected case?

1. Disable All - Disabling only non choosed gameplay modules? Then we must provide "Custom Gameplay" for full manual choosing modules
2. Disable All - Disable all except rendering module? then we needs implement some metanames/tags for modules. It must  handle requirement like "rendering tag", which say what you need one of rendering module.

**Comment by Cervator** [comment] 2020-09-01 02:01
So there are probably two phases to this topic.

1) Fixing current buggy behavior: Disable all should deactivate all modules _except_ the actively selected gameplay template and its mandatory dependencies. This would include disabling CoreRendering (but it is a dependency on most if not all gameplay templates at present). Not too hard, but not alone either, there are several config related bugs in this area.

2) Improving the overall setup: It used to be that BuilderSampleGameplay (now [TutorialMinimalEngineDemo](https://github.com/Terasology/TutorialMinimalEngineDemo), no longer in the Omega lineup) would be a minimal gameplay template you could effectively use as a "custom template" without involving CoreSampleGameplay and its increasingly larger set of dependencies. And now we _do_ need some special modules like CoreRendering to be handled differently, effectively serving as orphaned but mandatory dependencies _unless_ an alternative is provided. And we need to better distinguish between server and client specific modules (I think there are use cases for both). And support changing (at least some) modules in an existing save.

Probably this issue can be resolved by fixing 1), although it would be nice to also figure out the related bugs, such as why it _seems_ like a restart of the game may lose _all_ selected modules from the previous run, meaning you don't have any modules and no world to generate, at least in some cases. There can also be some weirdness overall when you activate/deactivate modules on the Advanced Game Setup screen we should review / stabilize.

**Comment by Cervator** [comment] 2020-10-23 04:22
Part of the buggy behavior in this area has probably been fixed by #4213, not sure if anything remains, haven't retested.

**Comment by niralverma** [comment] 2021-03-29 12:25
Disable All disables each and every gameplay. So lets add another button as Select option. That way the player can choose the gameplay he or she wants to keep or discard. And then when the player clicks on disable selected, only the selected gameplay are removed. That would be clearer from the user pov and cleaner from developer pov I think.

**Comment by jdrueckert** [comment] 2021-06-22 20:27
Cannot reproduce this anymore, so it seems to have been resolved, likely by #4213

**Closed by jdrueckert** 2021-06-22 20:27 UTC
Labels: Good First Issue, Status: Needs Investigation, Topic: UI/UX, Type: Bug
