### ISSUE TITLE
Performance problems 

### ISSUE THREAD

**Issue by Zireael07** [MovingBlocks/Terasology#2333] opened 2016-05-29 09:07 UTC
### What you were trying to do
Trying to play single player (Throughtout The Ages). 
Note: I tried core too, with the same effects.

### What actually happened
1) CPU spikes and a beige/blue screen (I guess that's the skybox) upon starting a game, persisting for 10 secs.
2) CPU spikes before the game figures out what chunks to show.
3) FPS drops when saving
4) Crashes/freezes when going into menu and/or exiting the game.

5) Crash when sitting in the menu  for a couple of minutes while writing this issue.

### How to reproduce
For the crash:
* Launch the game, wait for the saving to end.
* Go into main menu
* Launch Firefox, write the issue for a couple of minutes, see game crash report (Java out of memory).

### Log details and game version
Yesterday's dev version and/or latest stable. Make no difference. x86 vs x64 make no difference either

### Computer details

i5 @2.30 Ghz
Radeon 6630M
8 GB RAM
64-bit Windows 7
Java 8 update 91

**Comment by Translator5** [comment] 2016-05-29 13:43
Can't reproduce in Linux Mint 17.3.
JRE 1.8.0_91 (JAVA 8 update 91)

I can Open Firefox and play Java-games in Firefox while playing Terasology at the same time for hours. 
May you have installed a 32bit version of Java?
Or an add-on in Firefox is causing this problem?

I will try to reproduce it on my Win7.

**Comment by Zireael07** [comment] 2016-05-29 15:00
The other problems happen without having other apps open, too.

Other Java apps work fine (I know because I use one every day for work) and I can run very intensive games AND Unity editor at the same time without problems.

**Comment by Cervator** [comment] 2016-05-29 17:40
Any log files or you just see a clear out of memory error at the end?

TTA is a known resource-hog (with the exact symptoms you describe) and it hasn't aged well without a maintainer.  

It is odd though that you'd hit identical memory issues in Core. Normally we would indeed expect that to be some Java 32-bit issue or system constraints, but it sounds like you've got that covered.

You could try launching the game with more memory assigned and see if that helps:

`java -Xms128m -Xmx2048m -jar libs/Terasology.jar`

I'd recommend JoshariasSurvival instead of TTA as it is better maintained.

**Comment by Zireael07** [comment] 2016-05-30 07:09
Where do I look for log files? And where do I input those parameters? I just launch the game by double clicking the .exe

**Comment by Zireael07** [comment] 2016-05-30 14:59
Core or Josharias don't crash, but all other problems are there (CPU spikes/FPS drops I described).

When the game doesn't have to figure out chunks or save, it's going at 20-30 FPS. When saving or showing new chunks, it drops to 2-5 FPS, sometimes even below that.

**Comment by Cervator** [comment] 2016-05-30 16:36
To launch the game with parameters open a command prompt and go to the directory with the exe in it, then use that command. Or just use our launcher - it has drop-downs for stuff like that. 

https://github.com/MovingBlocks/TerasologyLauncher/releases

The game isn't super well optimized yet. If you press F3 then F4 it'll reveal some debug stats. That should include details on how much memory is assigned, how fast it cycles (gets assigned, grows, garbage collects), and which activities of the game are taking the most time. It would be useful to see a screenshot of that when the lag is bad (can't use F12 for that though as in-game screenshots lack the debug text)

**Comment by Josharias** [comment] 2016-05-31 20:45
I had some similar problems with my dual core computer.  There is something that changed a year or so ago to make the game stutter more when saving and generating chunks (at least I do not recall it stuttering like that before,  maybe it has always been like that).  Possibly some sort of threading magic to decrease priority of these background threads could help maintain the framerate?

**Comment by Zireael07** [comment] 2016-06-05 09:04
My computer is dual core too.
I wasn't quick enough to take a screen of F4 debug when it lagged, but at first glance I'm not seeing much difference between normal and laggy. Graphics taking the most, then chunks view.

#2337 seems to have improved the situation as far as 1) is concerned - there is a moment of stuttering when starting the game but it seems much shorter :fireworks:

**Comment by Cervator** [comment] 2016-06-05 18:21
Awesome, good to hear :-)

I suspect the remaining issues are just from our general level of performance. There are bound to be more optimizations like the one @Josharias just found, and they should trickle in over time. Likewise some of the intensive world gen for settings like TTA should get improved as well, when there is a maintainer available to make improvements anyway.

Since there likely isn't a specific issue remaining here I'll close this - but do feel free to comment further / submit new issues when you find something noteworthy!

**Closed by Cervator** 2016-06-05 18:21 UTC
Labels: Support
