### ISSUE TITLE
Strange rendering on Windows 10

### ISSUE THREAD

**Issue by TBBYT** [MovingBlocks/Terasology#3787] opened 2019-11-22 15:16 UTC
### What you were trying to do
I loaded in a game (also happens when making a new game)

### What actually happened
It loaded fine, but it had really wierd rendering

### How to reproduce

* Step 1
Create a new game or Load a saved game
* Step 2
This happens
![Terasology-191122163545-1152x720](https://user-images.githubusercontent.com/54937991/69435396-29e68100-0d48-11ea-832f-0c8c414e68fb.png)

#### Game version:
Stable release (normal)
78 - alpha
#### Log file:
https://drive.google.com/uc?id=1RcGlUebTcepZGbQBgUp12Inuz783dyq5&export=download
#### Save types:
This happened on two saves so far (all my saves):
Josharias Survival
MedievilCities
#### Graphics Settings
Minimal Preset
![image](https://user-images.githubusercontent.com/54937991/69437296-b181bf00-0d4b-11ea-86c9-6a0d4c993e90.png)
![image](https://user-images.githubusercontent.com/54937991/69437313-be061780-0d4b-11ea-8a7a-08d57633eb1c.png)

### Computer details
Typing `java -version` in console outputs:
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

And I also have have Java JDK 12.0.2 installed.

64-bit Microsoft Windows 10 Pro 10.0.17763.831
Intel Core i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
8.00 GB DDR4 RAM
18.9 GB Virtual Memory
Intel UHD Graphics 630
Total Available Graphics Memory: 4157 MB
Dedicated Video Memory: 128 MB

### Some Screenshots
![Terasology-191122155712-1600x847](https://user-images.githubusercontent.com/54937991/69436203-957d1e00-0d49-11ea-9c67-28e25a341ba6.png)
![Terasology-191122155723-1600x847](https://user-images.githubusercontent.com/54937991/69436204-9615b480-0d49-11ea-8a4e-bb8f3c737d1c.png)
![Terasology-191122155736-1600x847](https://user-images.githubusercontent.com/54937991/69436205-9615b480-0d49-11ea-8627-03c37346acbf.png)
![Terasology-191122155904-1600x847](https://user-images.githubusercontent.com/54937991/69436207-9615b480-0d49-11ea-8721-16dd86d0ea49.png)
![Terasology-191122155924-1600x847](https://user-images.githubusercontent.com/54937991/69436208-96ae4b00-0d49-11ea-9dde-c2620dd73739.png)
![Terasology-191122155941-1600x847](https://user-images.githubusercontent.com/54937991/69436209-96ae4b00-0d49-11ea-894c-4a48e73bb5bc.png)
![Terasology-191122155944-1600x847](https://user-images.githubusercontent.com/54937991/69436212-9746e180-0d49-11ea-891d-080372221073.png)
![Terasology-191122160243-1600x847](https://user-images.githubusercontent.com/54937991/69436213-9746e180-0d49-11ea-983b-fe24d4e03850.png)
![Terasology-191122160244-1600x847](https://user-images.githubusercontent.com/54937991/69436216-97df7800-0d49-11ea-9e03-afe2a117cb87.png)
![Terasology-191122163545-1152x720](https://user-images.githubusercontent.com/54937991/69436218-97df7800-0d49-11ea-8851-1e5013cfb3fa.png)

**Comment by Cervator** [comment] 2020-02-22 21:30
Hi @TBBYT and thanks for the detailed report!

We regularly hear of issues with those integrated Intel chips, but it is a little hard to tell if you're simply not getting parts of the world rendered or even simply spawned underground. First screenshot looks much like you'd see just from seeing the "back" of the world surface so to say (and a bunch of dark caves from JS). Yet in other spots clearly it seems like some block faces are just not rendering. Peculiar.

That's a pretty beefy machine too, no dedicated graphics card at all on it? Are you running the very latest drivers?

The previous stable build is pretty old at this point, but while it is ideal to try the latest I doubt that would change the rendering, not a lot of work there since. It would be interesting to re-visit that system sometime later after our rendering work has progressed some more, and hopefully resulted in better compatibility with lower-end graphics chips.

**Comment by TBBYT** [comment] 2020-02-27 07:33
@Cervator No, I don't have a dedicated graphics card, I didn't know how graphic cards worked when I bought my PC... :/
I just tried playing with a new world in Alpha 78, and I still have the same problem.

**Comment by DarkWeird** [comment] 2020-02-27 10:21
It is looks like a problem with chunk loading... Some chunks stuck in pre-final stage(generated or loaded, but not ready for rendering). at this stage done light processing.
@TBBYT can you make some screenshot with chunk wireframes?
@Cervator alpha 78 contains dag rendering? I see it in log.

**Comment by TBBYT** [comment] 2020-02-27 12:34
@DarkWeird I couldn't figure out how to enable chunk wireframes...
I also found an upside-down flower, mushroom & some tall grass:
![Terasology-200227132157-1152x720](https://user-images.githubusercontent.com/54937991/75440582-b4043e00-5964-11ea-8d06-e289ea5d70b4.png)
The terrain seems to be rendered upside-down in the background, too.
Here's my log file:
[Terasology-Josh_Survival_Alpha_78.log](https://github.com/MovingBlocks/Terasology/files/4261329/Terasology-Josh_Survival_Alpha_78.log)
I also just tested it on a virtual machine using Oracle VM Virtualbox running 64-bit Lubuntu 16.04.3, and besides extreme lag it worked fine:
![Terasology-200227141355-1152x714](https://user-images.githubusercontent.com/54937991/75444985-2d079380-596d-11ea-8113-beec1091217b.png)
![Terasology-200227141433-1152x714](https://user-images.githubusercontent.com/54937991/75444988-2ed15700-596d-11ea-90cd-e708dd8f3fe5.png)

[Console Log](https://github.com/MovingBlocks/Terasology/files/4261578/Console.txt)
[Terasology-Game_1.log](https://github.com/MovingBlocks/Terasology/files/4261579/Terasology-Game_1.log)
[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/4261580/Terasology-init.log)

In the launcher I set the initial memory of the game to 256mb and the maximum memory to 2gb.
Typing java -version in console outputs:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```
And my virtual machine's settings is:
Type: Linux
Version: Ubuntu (64-bit)
Base Memory: 3072mb
2 CPU cores with execution cap at 100%
Video Memory: 48mb
16 GB Dynamically allocated storage

**Comment by DarkWeird** [comment] 2020-02-28 05:53
Chunks wireframe - of F* button.
Irrc, f3 or f4 debug info, there prints key for debug help.

Which video driver in windows you use?
Have you directx installed?

Make init log for windows... There prints video driver information.

**Comment by TBBYT** [comment] 2020-03-19 08:39
I have DirectX 12:
![image](https://user-images.githubusercontent.com/54937991/77047489-7b88da80-69cd-11ea-9122-ea84d2509a90.png)
My video drivers:
![image](https://user-images.githubusercontent.com/54937991/77047254-1af99d80-69cd-11ea-824d-bef3b0f0b6c8.png)
![image](https://user-images.githubusercontent.com/54937991/77047315-3664a880-69cd-11ea-91c8-0e74e8f78d43.png)
I couldn't figure out how to enable chunk wireframes.

**Comment by skaldarnar** [comment] 2020-11-04 09:40
I haven't seen this in a while. We've migrated to LWJGL 3 in the meantime which means that most of the issues related to graphics/rendering reported some time ago are somewhat outdated. I vaguely remember some issue about "upside down chunk rendering" that was caused by some half-finished JOML migration (or something like that). Anyways, I'm closing this bug report as outdated.

Please feel free to open new a new issue if a similar problem arises in a more recent version of the game.

**Closed by skaldarnar** 2020-11-04 09:40 UTC
Labels: Bug, Support
