### ISSUE TITLE
Rendering Freezes/Breaks when Resizing Window when In-Game

### ISSUE THREAD

**Issue by prestidigitator** [MovingBlocks/Terasology#1747] opened 2015-05-27 07:39 UTC
Found in b2bcc42 on AMD FX-8350 with GeForce GTX 650 Ti Boost, running Arch Linux 64-bit (4.0.2-1-ARCH kernel with nvidia-340xx 340.86-9 driver) and OpenJDK 1.8.0_45.  Steps to reproduce:
1. Launch Terasology normally (gradlew runPC).
2. Create or load a single-player world and start game.
3. Maximize or unmaximize window.

Expected: window resizes and rendering continues as usual.

Observed: window resizes, but rendering becomes very odd and updates strangely or not at all.  Only crosshairs, HUD/menus, and possibly sun rays render normally.  Note smear of blue/white (sky?) in screenshot below.  It's the only thing that changed as I tried to look around or move.

Workaround: Return to menu and reload world.  Rendering resets to normal.
## Normal Rendering Prior to Resize

![terasologyresizerenderingbug_preresize](https://cloud.githubusercontent.com/assets/3741838/7831149/a447653e-0408-11e5-88c1-35e0d87fafb0.png)
## Broken Rendering after Resize

![terasologyresizerenderingbug_postresize](https://cloud.githubusercontent.com/assets/3741838/7831154/b4acf902-0408-11e5-967f-aff10458b519.png)
##

**Comment by emanuele3d** [comment] 2015-05-27 13:05
Uh-oh, that looks squarely up my alley.

I can reproduce the problem in develop. It appears some of the FrameBuffers are not being replaced with new ones matching the new size of the window. It doesn't surprise me as the resizing code, and especially its triggers, are a bit of a mess. And don't even think about taking screenshots with sizes not matching the current display! That might format your hard drive. Or worse!

Fear not however! I seem to have solved the problem in this [work branch](https://github.com/emanuele3d/Terasology/tree/IntroducingPostProcessorAndBuffersManager) of mine. Can you by any chance grab it and confirm? There still seems to be an issue as the image is slightly stretched on the Y axis after the resize/maximize/unmaximize, but the stretching disappears as soon as the player moves or rotates, which is perhaps something we can live with for the time being.

That branch is not going to make it directly into a PR however. We need to wait until the current [PostProcessor PR](https://github.com/MovingBlocks/Terasology/pull/1745) goes through. Then I can prioritize the work on the LwjglRenderingProcess class which will be renamed into FrameBufferManager. The functionality that refreshes the FrameBuffers when resizing occurs is there and I'll refactor it to match the code from the work branch.

So, should get fixed soon.

**Comment by Cervator** [comment] 2015-05-28 04:26
@prestidigitator - thanks for the catch, although no fair, that messed up version looks *way* more interesting than the black world I get with some streaky white :-(

@emanuele3d we need to keep track of these weird effects for goofy filters. I'm sure there's a potion you can drink one day that'll be supposed to make the world look like that :laughing:

**Comment by prestidigitator** [comment] 2015-05-28 11:28
Ha!  Yeah.  Gotta love the pastels.

@emanuele3d - Yes, the issue seems to be solved just as you describe on the emanuele3d/IntroducingPostProcessorAndBuffersManager branch.

**Comment by emanuele3d** [comment] 2015-05-28 12:54
@Cervator: I am sure we can find *proper* ways to render all the psychedelic potions you want to concoct. =)

@prestidigitator: good to know the refactored code solves the problem! I look forward integrating those changes in develop.

**Comment by emanuele3d** [comment] 2015-05-28 12:55
P.S. @Cervator: I certainly agree that it'd be good to keep track of these rendering bugs though, and make a gallery with them.

**Comment by Cervator** [comment] 2015-05-28 17:55
@emanuele3d make it so :D

(And sure, fix all the bugs while you're at it!)

**Comment by Cervator** [comment] 2017-03-26 22:46
Closing as fixed by #2844!

**Closed by Cervator** 2017-03-26 22:46 UTC
Labels: Bug, Rendering, UI
