### ISSUE TITLE
Got NPE during testing SelectModules game screen

### ISSUE THREAD

**Issue by ar0ne** [MovingBlocks/Terasology#3358] opened 2018-05-11 20:54 UTC
How to reproduce:
1. Open create new game screen
2. Open SelectModules screen and close it.
3. Open Details game screen and close it.
4. Try to open SelectModules again.
==> NPE

logs: https://pastebin.com/jYTnn37m

**Comment by mkienenb** [comment] 2018-05-11 20:57
Thanks for the report.   I was planning on taking a look at this code in a couple of hours and I'll add your item to my list.

**Comment by Cervator** [comment] 2018-05-11 21:08
FYI see #2509 and related issues, this sounds quite related. Specifically opening "Details" then closing it again leaves the module environment or something in a bad state (unless the next thing you do is start the game)

I believe this will be sorted out with @TheFlash98's GSOC item as it involves reordering these menu screens. Not that I'd turn out a quick and easy shorter term fix :-)

**Comment by mkienenb** [comment] 2018-05-12 15:04
This is a pretty weird one.   It's NPE'ing on sortedModules.
But sortedModules is set on initialise() and should not be able to revert back to null once set.

The only thing I can think of is that the SelectModulesScreen has been reconstructed and we're not using the one which was previously-initialized.   Maybe this is due to the clearing of the environment (reloaded the modules?) and this clearing doesn't re-initialise the NUI widgets when it recreates them. 

In any case, the cause wasn't what I thought it would be.   Somehow the fix would have to insure that initialise() was called again for this object.  I'm going to let someone else figure it out since I don't see a quick and easy fix.

**Comment by Cervator** [comment] 2018-06-18 02:32
Closing this as rendered obsolete by #3399 being merged - UI overhaul of involved screens :-)

**Closed by Cervator** 2018-06-18 02:32 UTC
Labels: Architecture
