### ISSUE TITLE
Java JRE 9 Crash

### ISSUE THREAD

**Issue by Translator5** [MovingBlocks/Terasology#2250] opened 2016-03-22 21:01 UTC
**Terasology-menu.log Spam**
`21:48:44.891 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration`

**Terasology.init.log Spam**
`21:47:57.319 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration`

**Terasology-game_1.log**
`21:49:01.399 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Moderate
21:50:04.180 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
21:50:04.189 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoClassDefFoundError: com/sun/nio/zipfs/ZipFileSystemProvider
	at org.terasology.persistence.internal.SaveTransactionBuilder.build(SaveTransactionBuilder.java:77) ~[engine-1.0.0.jar:64, master, 64, alpha]
	at org.terasology.persistence.internal.ReadWriteStorageManager.createSaveTransaction(ReadWriteStorageManager.java:258) ~[engine-1.0.0.jar:64, master, 64, alpha]
	at org.terasology.persistence.internal.ReadWriteStorageManager.startSaving(ReadWriteStorageManager.java:399) ~[engine-1.0.0.jar:64, master, 64, alpha]
	at org.terasology.persistence.internal.ReadWriteStorageManager.waitForCompletionOfPreviousSaveAndStartSaving(ReadWriteStorageManager.java:235) ~[engine-1.0.0.jar:64, master, 64, alpha]
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:128) ~[engine-1.0.0.jar:64, master, 64, alpha]
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:499) ~[engine-1.0.0.jar:64, origin/master, 64]
	at org.terasology.engine.TerasologyEngine.processPendingState(TerasologyEngine.java:492) ~[engine-1.0.0.jar:64, origin/master, 64]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:396) ~[engine-1.0.0.jar:64, origin/master, 64]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-1.0.0.jar:64, origin/master, 64]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:64, origin/master, 64]
Caused by: java.lang.ClassNotFoundException: com.sun.nio.zipfs.ZipFileSystemProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:385) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:na]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:262) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:na]
	... 10 common frames omitted
21:50:04.189 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
21:50:04.190 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot`

**Started the game with Java JRE 9**
`linux@LinuxUser ~ $ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+110)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+110, mixed mod`

I started the game, load a map, walked a minute and it froze, than the log was been shown to me.

_Linux Mint 17,3 ROSA 64bit
Terasology Launcher 3,0,0
Terasology Stable Version 64_

**Comment by Cervator** [comment] 2016-03-23 01:56
Hey there @Translator5 - it is interesting to know somebody tried Terasology on Java 9, but I'm not sure it is something we could or should do anything about yet being that Java 9 is still more than a year away :-)

Would you agree? We can probably close this issue if so. Thanks for the experiment though!

**Comment by msteiger** [comment] 2016-03-23 07:13
This seems to be related or caused by http://openjdk.java.net/jeps/238
As long as folks are still working on this, I'd rather not rely on it. Let's wait a few more weeks/months..

**Comment by Cervator** [comment] 2016-04-03 03:00
Going to close this for now since Java 9 is a long way out.

**Closed by Cervator** 2016-04-03 03:00 UTC
