### ISSUE TITLE
Regression caused by teramath merge (PR #1417): Hand torch light is broken

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#1527] opened 2015-01-15 16:10 UTC
Pull request #1417 by @msteiger broke the nice inhand lighting for me. It no longer fading but goes from 100% to 0% instantly. If you aren't close to something you don't see any light at all.

Revision before merge in which inhand light still works properly:
3dbe8441f210eb285db261a73455dfee4f2b77ea

Screenshot:

![inhandtorchgood](https://cloud.githubusercontent.com/assets/3511/5761020/c7b40546-9cd8-11e4-9947-e90ac05bf9df.png)

Merging commit, in which the inhand light is broken:
0ee37bdd1a508d8a0e59f97e45f2ad48789c1503

Screenshot:
![inhandtorchbad](https://cloud.githubusercontent.com/assets/3511/5761021/c7b5a518-9cd8-11e4-8739-dbd8ae6bad06.png)

Please note that @emanuele3d already made with #1507 some changes to how torches get rendered.
##

**Comment by Cervator** [comment] 2015-01-15 16:18
Interesting! It wasn't nearly this total for me, but it certainly seems like the same kind of interesting. Thanks for the detective work on the root cause, probably some minor math quirk causing it :-)

**Comment by emanuele3d** [comment] 2015-01-15 21:48
Hmmmm... the plot thickens! I'm pretty sure the issues are related. Good to have a commit to look at for differences with the previous, working commit. Thank you @flo, this will hopefully speed up the search for a solution.

**Comment by msteiger** [comment] 2015-01-18 11:27
We did some more digging a few days ago and your fix in #1507 seemed to fix the issue. I wonder what part of TeraMath could be linked to this. Do you have a pointer to where the torch light is computed?

**Comment by Cervator** [comment] 2015-10-11 23:42
@flo could you let us know if this has since stopped happening? Been a while.

**Comment by unpause** [comment] 2015-10-12 17:58
@Cervator Hey Cerv, How requested in old #1486 i will give you an update. The problem still exists for me.

**Comment by Cervator** [comment] 2015-10-12 18:20
Thanks a lot for following up @unpause ! :-)

We'll get this bug evicted fully one day

**Comment by emanuele3d** [comment] 2015-10-13 08:04
Sorry everybody, I'm still not in a position to get back on track with
everything, especially with finishing the refactoring and documenting of
the top-level classes of the rendering engine. This should at least enable
other people to navigate and eventually fix any rendering code more easily.

I should be able to get back onto coding in December as a number of
family-related things will be out of the way. I'd recommend to keep this
issue active or re-open a relevant, previously closed issue.

That been said, I am monitoring discussions and now I'm also monitoring
again the GitHub feed. I'll jump in as I'm doing now if I feel I can
contribute or I can at least give some hope. ;)

**Comment by Cervator** [comment] 2015-10-13 16:47
@emanuele3d that's perfectly understandable. Appreciate the update and December is fine :-)

**Comment by unpause** [comment] 2015-10-13 17:07
@Cervator I will come back to when i have time and motivation ;)

A thing to mention is that the issue that i have with the black stripes does only happen in this game.

**Comment by Cervator** [comment] 2015-10-13 17:33
@unpause awesome! Looking forward to it :-)

**Comment by unpause** [comment] 2016-03-24 17:08
Update: The issue still exists

**Comment by Cervator** [comment] 2016-03-26 02:44
Heya @unpause good to hear you're still out there! And fun timing! I *just* merged PR #2247 which did a bunch of light tweaking. Able to retest with the latest dev build now that it is merged? :-)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

@flo do you get it still?

**Comment by unpause** [comment] 2016-03-26 07:19
Nope, I still get this weird effect with the stripes. :-(

**Comment by pollend** [comment] 2016-03-26 18:50
I'm not sure how to reproduce this.

**Comment by Cervator** [comment] 2016-03-28 02:36
It may be GPU specific at this point :/

Thus wondering if anybody else still gets it. I *think* we fixed something, maybe the vast majority of cases. @unpause has the sphere effect gone away leaving only the graphic artifacts with stripes?

(old screenie for reference: http://imgur.com/kKkNjkD)

I suspect the stripes are a different issue and likely tied to GPU (older mobile card) which we may not be able to fix.

**Comment by pollend** [comment] 2016-03-28 02:47
That looks like a problem with the shadowmap. Maybe playing around with the depth stencil in the FBO may be able to resolve this.   @emanuele3d has a better idea. I believe this problem is due to a floating point error in the shadowmap. Maybe raising the bias can resolve the shadow problem in the image that Cervator linked. 

The problem looks similar to this: http://www.opengl-tutorial.org/assets/images/tuto-16-shadow-mapping/1rstTry.png

http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/

**Comment by unpause** [comment] 2016-03-28 10:00
Nope, it's still all there.

Pictures: [http://imgur.com/a/xhy8U](http://imgur.com/a/xhy8U)

**Comment by pollend** [comment] 2016-03-28 14:41
What is the graphics card?

**Comment by unpause** [comment] 2016-03-28 14:51
@pollend ATI Mobility Radeon HD 4650

**Comment by skaldarnar** [comment] 2019-04-08 20:27
Fixed - torches held in hand emit light.

**Closed by skaldarnar** 2019-04-08 20:27 UTC
Labels: Bug, Rendering
