### ISSUE TITLE
Crash after generating new world

### ISSUE THREAD

**Issue by srakitnican** [MovingBlocks/Terasology#1998] opened 2015-10-29 21:18 UTC
Downloaded latest stable version, extracted the archive and ran run_linux.sh. On new world generation game crashes: http://pastebin.com/E0JUzu6n

Tried switching gameplay template to Core Gameplay and game ran, crash occures on Light & Shadow setting.

Running Fedora 22 / OpenJDK 1.8

**Comment by Cervator** [comment] 2015-10-30 06:10
Hi there. This should caused by #1986 and fixed within the next few days. Thanks for the report :-)

**Comment by Cervator** [comment] 2015-10-31 04:07
Fixed in the latest develop build: http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

@srakitnican feel free to try again with the new build. Should be a full release in a day or two

**Closed by Cervator** 2015-10-31 04:07 UTC
Labels: Support
