### ISSUE TITLE
Goodie chest the player starts with in CoreSampleGameplay is empty

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3067] opened 2017-08-14 04:04 UTC
### What you were trying to do

Do final testing for Alpha 8 - Core. I placed the chest the player starts with and expected it to contain stuff

### What actually happened

No stuff!

Probably a simple issue breaking how the starting player inventory is set up. See `PlayerStartingInventorySystem` and maybe the `InventoryAuthoritySystem` - might even be bite-sized for somebody able to step through code to see where the items get lost (probably set a breakpoint in `onPlayerSpawnedEvent` in `PlayerStartingInventorySystem`

### How to reproduce

* Start the game with CoreSampleGameplay selected and any world
* Place the chest you start with in your toolbar into the world
* Open the chest with `e` - no stuff!

High priority since that chest contains all kinds of useful goodies to help demo the game.

**Comment by xrtariq2594** [comment] 2017-08-15 18:47
It appears the problem is bigger than just the goodie chest.

Apparently, if you place items into the chest when it's in the world, destroy the chest, collect it, place it again, and open it, the items you originally placed in the chest will be gone. So, the items are not being transferred properly.

**Comment by jellysnake** [comment] 2017-08-23 22:45
So, just for anyone else looking at this:

On a headless server the items do not vanish when a chest is placed.  
Whilst the user is holding a chest the items are still present within that chest.  
The items have gone missing by the time the `onPlaced` method of `blockInventorySystem` is called.
The items also are missing before the `OnBlockPlacedEvent

**Comment by xrtariq2594** [comment] 2017-08-27 17:34
> The items also are missing before the OnBlockItemPlaced event is called

Yep, I can confirm that as well @jellysnake. I verified that in the `onPlaceBlock` method of `BlockItemSystem.java`. Something seems to happen between holding the chest, and sending the `OnBlockItemPlaced` event. I guess we'll need to look further up the chain.

**Comment by jellysnake** [comment] 2017-08-28 13:57
@Cervator and @Anthodeus have found that it seems to be caused by or at least related to #2810. This fits with the behaviour of the bug

**Comment by xrtariq2594** [comment] 2017-08-28 17:41
Yep, can confirm it @jellysnake. After reverting to the commit just before that one, it starts working again.

**Closed** 2017-09-02 04:45 UTC
Labels: Blocker, Bug
