### ISSUE TITLE
black screen in Terasology 

### ISSUE THREAD

**Issue by MoamenA** [MovingBlocks/Terasology#5058] opened 2022-07-21 14:49 UTC
I Download Terasology From official website and install the last release and open but the world in black and do not see ant thing My
Full requirements Is 
I5 3470 
8 giga ram
Intel HD 2500 support Open Gl 4.0

**Comment by jdrueckert** [comment] 2022-09-25 20:47
Closing this as it seems to be a duplicate of https://github.com/MovingBlocks/Terasology/issues/5057

**Closed by jdrueckert** 2022-09-25 20:47 UTC
