### ISSUE TITLE
Came crash, '/ by zero'.

### ISSUE THREAD

**Issue by tzunix** [MovingBlocks/Terasology#4834] opened 2021-07-28 12:40 UTC
### What you were trying to do
Was gathering sticks in Josariah's survival
### What actually happened
Game closed on me
### How to reproduce
Playing i gather. Second time I had this on a post-5.0.0 release version
* Step 1
* Step 2
* Step 3

### Log details and game version

5.1.0_snapshot584

```
14:27:59.424 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
14:27:59.426 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
14:28:24.440 [main] INFO  o.t.e.s.EventualSkillAuthoritySystem - EntityRef{id = 1180, netId = 0, prefab = 'engine:player'} stopped training skill
14:28:24.440 [main] INFO  o.t.e.systems.SkillsAuthoritySystem - EntityRef{id = 1180, netId = 0, prefab = 'engine:player'} given skill manuallaboreventualskills:craftingskill level 2
14:28:24.440 [main] INFO  o.t.e.s.EventualSkillAuthoritySystem - EntityRef{id = 1180, netId = 0, prefab = 'engine:player'} completed training skill manuallaboreventualskills:craftingskill
14:28:59.430 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
14:28:59.432 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
14:29:59.443 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
14:29:59.444 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
14:30:59.449 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
14:30:59.451 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
14:31:48.600 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: / by zero
	at org.terasology.nui.widgets.UIIconBar.getPreferredContentSize(UIIconBar.java:110)
	at org.terasology.nui.canvas.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:383)
	at org.terasology.nui.layouts.relative.RelativeLayout.getRegion(RelativeLayout.java:143)
	at org.terasology.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:85)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.layers.hud.CoreHudWidget.onDraw(CoreHudWidget.java:45)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.layers.hud.HUDScreenLayer.onDraw(HUDScreenLayer.java:149)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:577)
	at org.terasology.engine.core.modes.StateIngame.renderUserInterface(StateIngame.java:218)
	at org.terasology.engine.core.modes.StateIngame.render(StateIngame.java:202)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:76)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:513)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:464)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
14:31:48.601 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...
14:31:48.824 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
14:31:48.838 [main] INFO  o.t.e.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
14:31:48.844 [main] INFO  o.t.e.n.internal.NetworkSystemImpl - Client disconnected: Player86411
14:31:48.847 [main] INFO  o.t.engine.logic.console.ConsoleImpl - [NOTIFICATION] Player "Player86411" has left the game
14:31:48.848 [main] INFO  o.t.e.n.internal.NetworkSystemImpl - Network shutdown
```

**Comment by skaldarnar** [comment] 2021-07-29 22:30
Thanks for reporting this @tzunix !

From the logs it looks like an actual issue, thus I'm re-opening this issue.

**Comment by skaldarnar** [comment] 2023-07-02 16:08
Duplicate of #4575.

**Closed by skaldarnar** 2023-07-02 16:08 UTC
Labels: Category: Crash
