### ISSUE TITLE
Game crash on listing info for a bad state server in the master list

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1781] opened 2015-06-19 17:12 UTC
This one seems somewhat odd. Was attempting to test @minnesotags' server after a refresh and we also had a new server from war_sloop (GitHub: @ange-black69) online at evorigin.tk

Probably some minor issue is making me time out against @minnesotags' server but we'll sort that out and it is separate. @Calinou's server is offline for sure and that's fine, it also just correctly showed a connection failure. But when I got to the new server, which I've previously connected to from source the game listened for an update for a few moments then crashed outright:

```
13:02:49.907 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (3900735), capping to 1000
13:03:29.904 [New I/O boss #2] WARN  o.t.n.i.ServerInfoRequestHandler - Could not query server info: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: terasology.tuffkidtek.com/63.231.198.19:25777
13:03:47.203 [New I/O boss #2] WARN  o.t.n.i.ServerInfoRequestHandler - Could not query server info: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: mt.nerdpol.ovh/149.91.81.111:25777
13:03:48.782 [New I/O worker #1] INFO  o.t.n.i.ClientHandshakeHandler - Received Server Hello
13:03:48.783 [New I/O worker #1] INFO  o.t.n.i.ClientHandshakeHandler - No existing identity, requesting one
13:03:58.434 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
    at org.terasology.rendering.nui.layers.mainMenu.JoinGameScreen.getWorldText(JoinGameScreen.java:335) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layers.mainMenu.JoinGameScreen.access$700(JoinGameScreen.java:65) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layers.mainMenu.JoinGameScreen$14.get(JoinGameScreen.java:312) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layers.mainMenu.JoinGameScreen$14.get(JoinGameScreen.java:306) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.widgets.UILabel.getText(UILabel.java:65) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.widgets.UILabel.getPreferredContentSize(UILabel.java:87) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:326) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.ColumnLayout.calculateRowSize(ColumnLayout.java:195) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.ColumnLayout.getPreferredContentSize(ColumnLayout.java:221) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:326) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.getRegion(RelativeLayout.java:145) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:68) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:371) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.ColumnLayout.onDraw(ColumnLayout.java:174) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:371) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:69) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:371) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:103) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:371) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:376) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.engine.modes.StateMainMenu.render(StateMainMenu.java:152) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:120) ~[engine-0.53.1.jar:55, master, 55, pre-alpha]
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:463) ~[engine-0.53.1.jar:55, origin/master, 55]
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:374) ~[engine-0.53.1.jar:55, origin/master, 55]
    at org.terasology.engine.Terasology.main(Terasology.java:152) [Terasology.jar:55, origin/master, 55]
13:03:58.434 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

Unfortunately no very enlightening log there, and war_sloop's server could be in some bad state, but it doesn't seem like asking for a server status should be able to crash the game client.

I tried with both stable 55 binary (matched with @minnesotags' server) and very latest develop from source, same result.

Also noticed by chance that the CR seems to still show older log sets when it comes to menu/init - might be of interest to @msteiger 

![lotsoflogs](https://cloud.githubusercontent.com/assets/1063833/8258676/ce78691e-1684-11e5-9118-c8832ed167d6.png)
##

**Comment by msteiger** [comment] 2015-06-19 18:48
I tested the new server yesterday and it worked fine for me. The @minnesotags server timed out as well, though. Will have a look asap.

Previously, CrashReporter provided access to all available log files. I restricted it to show only the current game, but all sessions/files. If that's still too much, we can restrict it further.

**Comment by Cervator** [comment] 2015-06-19 21:02
Looks like the server was in a crashed state - had run out of memory trying to start TTA or some time after starting it.

https://gist.github.com/ange-black69/abaf15b6e14367681903

So that might explain why it was only reacting differently later and to reproduce this you might need a server in a partially crashed state. All the way down and you'll get a time out. All the way up probably works fine. Out of memory = client go boom

@msteiger yeah I recall you made it only show the most recent world log file. I guess most recent menu + init might be another good constraint :-)

**Comment by msteiger** [comment] 2015-06-20 13:53
Hmm ... I cannot reproduce the issue. I checked out `engine-0.53.1`, which seems to correspond to the tag `stable53`, but [JoinGameScreen.java line 335](https://github.com/MovingBlocks/Terasology/blob/stable53/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java#L335) is empty.

**Comment by Cervator** [comment] 2015-06-20 17:23
stable55 tag puts it at

`codedModInfo.add(FontColor.getColored(entry.toString(), color));`

https://github.com/MovingBlocks/Terasology/blob/stable55/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java#L355

Maybe somehow in its crashed state (or even just running TTA?) the server was able to return bad data in `serverInfoMessage.getModuleList()` ?

**Comment by skaldarnar** [comment] 2020-07-29 08:15
Lot's of things changed since 2015, including some work and fixes of the server listing screen. Closing this as outdated.

**Closed by skaldarnar** 2020-07-29 08:15 UTC
Labels: Bug, Multiplayer
