### ISSUE TITLE
World Rendering Issue - shadows/lighting, player-centered sphere effect

### ISSUE THREAD

**Issue by unpause** [MovingBlocks/Terasology#1486] opened 2015-01-03 18:20 UTC
There are small black stripes all over the World. It's the same on all graphic settings. 

Logfile: http://pastebin.com/kxtTkAd9
Screenshot: http://imgur.com/kKkNjkD

**Comment by Cervator** [comment] 2015-01-03 18:40
Nothing obvious in the log, it is *probably* just a general issue with the specific video card - ATI Mobility Radeon HD 4650 - as we currently do not always get along the best with mobile cards :-)

Video card driver update is the only thing I can think to check right now, otherwise this might be something a 3d wizard can spot as related to a particular rendering tweak at some point in the future

**Comment by unpause** [comment] 2015-01-03 18:48
I have already the latest drivers i can have ... the newest is only for Win8 and newer and i have Win7

**Comment by Cervator** [comment] 2015-01-03 18:51
Yep, I figured as much :-(

There is *probably* a way to fix it, but we need a 3d wizard to puzzle it out sometime :-)

**Comment by msteiger** [comment] 2015-01-03 20:31
Can you tweak the video settings somehow to track it down more?

**Comment by emanuele3d** [comment] 2015-01-03 20:43
Interesting! It almost looks like the PixelFormat for some of the layers
used to produce the final image on screen is incorrect, resulting in pixel
data being sent in the wrong order or having gaps. But I'm just
speculating.

Unpause, can you use the F5/F6 keys to see if the problem is limited to
only some of the debug renderings? I probably won't be able to solve it any
time soon, but it'd be useful to narrow the problem.

**Comment by unpause** [comment] 2015-01-04 09:29
It doesn't happen when the shadows are turned off. And when i have a torch in my hand this happens: http://imgur.com/V1YG7DL its like fixed in the world but now when i go left it also goes left ... when i go forward it also goes forward ... when i look to the left or right it doesnt move

**Comment by Cervator** [comment] 2015-01-04 21:33
That sphere impact looks familiar - we had similar issues with shadows in that kind of shape before. So yay! This is probably fixable now that we have more details. Thanks :-)

**Comment by Cervator** [comment] 2015-01-08 21:39
Speaking of the sphere thing, just noticed this:

![terasology-150108161826-1152x720](https://cloud.githubusercontent.com/assets/1063833/5671249/4bb452e0-9754-11e4-8ed7-4726b0103985.png)

In most cases it is just a sphere, it interacts funny with nearby blocks at your height level. I don't *think* this has been a thing before, but not sure how long back to go to check it.

Merging the LWJGL 2.9.2 upgrade didn't seem to change anything, but @unpause feel free to recheck with the latest dev build just in case. Well, in a few minutes after it builds, anyway :D

Definitely a topic for a 3d wizard sometime, tweaking the issue title slightly

**Comment by unpause** [comment] 2015-01-09 15:19
Still the same as before.

**Comment by emanuele3d** [comment] 2015-01-09 21:30
Not a wizard by a long shot, but given that I'm the only one messing with
that part of the code... I hear ya! ;)

**Comment by Cervator** [comment] 2015-01-09 21:46
Centerered - one of these days I'll get the title right.

@unpause - thanks

**Comment by emanuele3d** [comment] 2015-01-10 09:18
For the sake of posterity, it appears to be a problem at least related, if not completely due to, the Light Geometry Stencil Pass. See the **WorldRendererLwjgl** class, methods **renderLightGeometryStencil()** and subsequent **renderLightGeometry()**. In particular, at the time of the writing disabling (commenting out) the stencil pass re-enables torch-in-hand lighting, at behavior that seem to have been lost in the recent past.

**Comment by Cervator** [comment] 2015-01-12 03:23
Deal! I can confirm a held torch behaves (for me) again :-)

As long as you keep up this great work I'm not too worried if a few things only get part of the way per PR - we're heading in the right direction!

**Comment by Cervator** [comment] 2015-01-12 03:26
Posted right comment to wrong issue :D

@unpause - can you retry with the latest dev build now? It fixes the problem I mention affecting me above, although it is still possible your issue is distinct

http://jenkins.terasology.org/job/Terasology/lastSuccessfulBuild/artifact/build/distributions/Terasology.zip

**Comment by unpause** [comment] 2015-01-14 14:13
Still the same issues.

**Comment by Cervator** [comment] 2015-01-14 14:26
Righto, thanks again for the update.

**Comment by Cervator** [comment] 2015-10-11 23:41
Closing as likely out of date / reworked since the report. Newer issue #1527 covers much the situation anyway but has more info.

@unpause if you're still out there it may well be worth trying the latest build to see if you can still replicate :-)

**Closed by Cervator** 2015-10-11 23:41 UTC
Labels: 3D-Wizardry, Bug, Support
