### ISSUE TITLE
Goo Keeper Template Game Crashing

### ISSUE THREAD

**Issue by ghost** [MovingBlocks/Terasology#4904] opened 2021-09-11 19:24 UTC
### What you were trying to do
Play the Goo Keeper template game

### What actually happened
Loaded Goo Keeper game and within about 30 seconds of coming in close proximity to the "Goos", they began to move back and forth faster and faster until the application crashed.  Could possibly be mem leak/overflow, but not sure.  I'll leave that to the pros :)

### How to reproduce

Startup the app, load the Goo Keeper template game

### Log details and game version
Alpha v5.1.1

### Computer details
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.11.0-34-generic
Architecture: x86-64

**Comment by runlevel-4** [comment] 2021-09-19 16:51
> ### What you were trying to do
> 
> Play the Goo Keeper template game
> ### What actually happened
> 
> Loaded Goo Keeper game and within about 30 seconds of coming in close proximity to the "Goos", they began to move back and forth faster and faster until the application crashed. Could possibly be mem leak/overflow, but not sure. I'll leave that to the pros :)
> ### How to reproduce
> 
> Startup the app, load the Goo Keeper template game
> ### Log details and game version
> 
> Alpha v5.1.1
> ### Computer details
> 
> Operating System: Ubuntu 20.04.3 LTS
> Kernel: Linux 5.11.0-34-generic
> Architecture: x86-64

This was me when the game was working previously

**Comment by jdrueckert** [comment] 2022-01-07 17:14
@runlevel-4 I wasn't able to reproduce this with Terasology 5.1.1 :thinking:
Can you reliably reproduce this on your machine or was this only a sporadic issue?

**Comment by jdrueckert** [comment] 2022-08-27 12:00
Closing this as author didn't respond and Goo Keeper is removed since Terasology 5.3.0-rc.2

**Closed by jdrueckert** 2022-08-27 12:00 UTC
Labels: Type: Bug, Category: Gameplay Content, Status: Needs Author Input, Category: Crash
