### ISSUE TITLE
Failed to initialise Terasology java.lang.RuntimeException: Can not initialize graphics device.

### ISSUE THREAD

**Issue by cognoscentis** [MovingBlocks/Terasology#2824] opened 2017-03-13 15:08 UTC
### What you were trying to do
First time start this game
### What actually happened
Error message and then game close
### How to reproduce

* Step 1 
Take MSI GT72s 6QD Dominator laptop =)
* Step 2 
Run last stable version of Terasology

### Log details and game version

[terasology_2017-03-13_17-59-48.872.txt](https://github.com/MovingBlocks/Terasology/files/838609/terasology_2017-03-13_17-59-48.872.txt)

### Computer details
MSI GT72s 6QD Dominator

**Comment by cognoscentis** [comment] 2017-03-13 15:28
Update Nvidia drivers to last version (378.78) and problem disappeared

**Comment by Malanius** [comment] 2017-03-13 17:07
Probably duplicate of #2790 and #2802 
That driver version crashed a bit more than Terasology :)

**Comment by cognoscentis** [comment] 2017-03-13 18:22
I think that this issue can be closed?

**Comment by skaldarnar** [comment] 2017-03-13 18:48
If it is solved with latest drivers this can be closed indeed. Thanks for reporting _and_ reporting back on it!

**Closed by skaldarnar** 2017-03-13 18:48 UTC
