### ISSUE TITLE
Immediate Crash Upon Right Click On Block

### ISSUE THREAD

**Issue by Bobondacob** [MovingBlocks/Terasology#2953] opened 2017-05-20 18:10 UTC
### Log file: 
`<: https://drive.google.com/uc?id=0B5l2RT_UOCXRRWE3UFhpNFRFSVE&export=download :>`
 **ALPHA TerasologyStable 2017-3-20**

### FX-8350, 16GB RAM, 1050ti, running Windows 10 Professional x64 with Java JRE

**Comment by oniatus** [comment] 2017-05-20 18:33
Thanks for the report, looks like a version issue.
Lot's of errors like
```
13:54:17.093 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab Core:defaultBlockParticles with inputs [/Core/assets/prefabs/particleEffects/defaultBlockParticles.prefab]
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'particleDataSprite'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'energyRangeGenerator'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'velocityRangeGenerator'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'scaleRangeGenerator'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'textureOffsetGenerator'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'accelerationAffector'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'velocityAffector'
13:54:17.093 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'particleEmitter'
```

and the final crash
```
13:56:30.864 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoClassDefFoundError: org/terasology/particles/components/ParticleDataSpriteComponent
	at org.terasology.logic.health.BlockDamageAuthoritySystem.onPlayBlockDamageCommon(BlockDamageAuthoritySystem.java:126)
	at org.terasology.logic.health.BlockDamageAuthoritySystem.onDamagedCommon(BlockDamageAuthoritySystem.java:114)
	at org.terasology.logic.health.BlockDamageAuthoritySystem.onDamaged(BlockDamageAuthoritySystem.java:93)
	at org.terasology.logic.health.BlockDamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.health.HealthAuthoritySystem.doDamage(HealthAuthoritySystem.java:174)
	at org.terasology.logic.health.HealthAuthoritySystem.checkDamage(HealthAuthoritySystem.java:191)
	at org.terasology.logic.health.HealthAuthoritySystem.onDamage(HealthAuthoritySystem.java:183)
	at org.terasology.logic.health.HealthAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.health.HealthAuthoritySystem.damageEntity(HealthAuthoritySystem.java:116)
	at org.terasology.logic.health.BlockDamageAuthoritySystem.onAttackHealthlessBlock(BlockDamageAuthoritySystem.java:193)
	at org.terasology.logic.health.BlockDamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.characters.CharacterSystem.onAttackRequest(CharacterSystem.java:129)
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.characters.CharacterSystem.onAttackRequest(CharacterSystem.java:104)
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:174)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:336)
	at org.terasology.input.InputSystem.update(InputSystem.java:279)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:179)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
Caused by: java.lang.ClassNotFoundException: Failed to find or load class org.terasology.particles.components.ParticleDataSpriteComponent
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.terasology.module.sandbox.ModuleClassLoader.loadClass(ModuleClassLoader.java:121)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 common frames omitted
Caused by: javassist.NotFoundException: org.terasology.particles.components.ParticleDataSpriteComponent
	at javassist.ClassPool.get(ClassPool.java:452)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:145)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:142)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:142)
	... 46 common frames omitted
```
The last one is a bit odd because the class `ParticleDataSpriteComponent` and the calling code from `BlockDamageAuthoritySystem.onPlayBlockDamageCommon(BlockDamageAuthoritySystem.java:126)` have been added in the same PR: https://github.com/MovingBlocks/Terasology/pull/2728

Which build are you using? I was unable to reproduce it with the latest develop from http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

**Comment by Cervator** [comment] 2017-05-20 20:14
Huuuuge list of modules activated might relate. Try to just run "CoreSampleGameplay" or "JoshariasSurvival" please :-)

"ALPHA TerasologyStable 2013-3-20" also worries me a bit. A stable release from 2013? We weren't even Alpha back then. Just updated modules via in-game module browser or something?

The particle stuff is #2941 and may also relate since a few affected modules have not yet been rebuilt against the latest engine version, which would cause them to fail. Using a mix of different engine and module versions can result in odd errors.

Poking @MaxBorsch for reference since we do need to get that one fixed :-)

**Comment by Bobondacob** [comment] 2017-05-21 03:29
Obviously pretty new to the program. Wasn't sure how many was too much or too little, and yeah, I can see how that could cause problems now. It is the latest Omega build.
<The 2013 was a typo, fixed now.>

**Comment by Cervator** [comment] 2017-05-21 03:40
Oh phiew then, that part really had me confused, hehe :D

Thanks for following up! Let us know if it works out better just sticking with a template. Some modules still may not work due to #2941 but so long as you stick with the latest Omega stable zip without updating modules in-game (since then you'll get modules not considered stable) you should be ok

**Comment by Cervator** [comment] 2017-07-08 04:04
Closing this as complete as all known old particle system references have now been updated / cleared out :-)

Latest dev build should be fine now and a new stable should be out soon.

**Closed by Cervator** 2017-07-08 04:04 UTC
Labels: Support
