### ISSUE TITLE
Chest name displaying incorrectly

### ISSUE THREAD

**Issue by Rukki13** [MovingBlocks/Terasology#5232] opened 2024-04-01 20:58 UTC
Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: Windows 11 Home
Onboard / Dedicated Graphics: GTX 1650 TI
Java Version:  8 Update 202

**Problem:** When I look at the chest block, its name isn't displayed correctly.
![image](https://github.com/MovingBlocks/Terasology/assets/97735409/380d0208-6de0-49c3-a0c8-eeca7971f18c)
**Game Template:** Lost

I will work on it and push the code.

**Comment by Rukki13** [comment] 2024-04-01 22:17
Where are the blocks properties defined for a certain block? The template is Lost

**Comment by BenjaminAmos** [comment] 2024-04-02 18:54
The tooltips come from the [WorldlyTooltip](https://github.com/Terasology/WorldlyTooltip) module. That particular string looks like a translated ("i18n"/internationalisation) string. The main ones can be found in the files at [`engine/src/main/resources/org/terasology/engine/assets/i18n`](https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/resources/org/terasology/engine/assets/i18n)).

The name string for that particular chest though is defined in https://github.com/Terasology/CoreAdvancedAssets/blob/develop/assets/i18n/game.lang. That placeholder string is supposed to be replaced by the translation system, so the issue may lie within the `WordlyTooltip` module itself.

**Comment by BenjaminAmos** [comment] 2024-04-02 18:56
NUI's [`ToStringTextRenderer`](https://github.com/MovingBlocks/TeraNUI/blob/master/nui/src/main/java/org/terasology/nui/itemRendering/ToStringTextRenderer.java) class might have been intended to do it also, although you'll need to pass a translator instance into it directly.

**Comment by soloturn** [comment] 2024-05-04 17:01
@Rukki13 how can one quickest find such a chest?

**Comment by Rukki13** [comment] 2024-05-05 13:01
I entered the first house I've encountered

**Comment by jdrueckert** [comment] 2024-05-08 09:49
@Rukki13 I'm closing this as this is a duplicate of https://github.com/Terasology/CoreAdvancedAssets/issues/6
In the original issue you'll find some more information about the assumed problem and ideas how to fix it.

**Closed as not planned by jdrueckert** 2024-05-08 09:49 UTC
Labels: Type: Bug, Status: Needs Investigation, Topic: Stabilization
