### ISSUE TITLE
Game not loading anymore - Display problem apparently. 

### ISSUE THREAD

**Issue by zeokav** [MovingBlocks/Terasology#2790] opened 2017-02-15 14:44 UTC
### What you were trying to do
Run the game after building it from the new source. 

### What actually happened
Game builds with no errors (Except that CrashReporter class does not exist, which I commented out), splash screen starts up fine, but towards the end of loading, the game crashes. Last message logged is - 
20:06:27.921 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)

### How to reproduce
* Build from the latest source
* Look at the crash

### Log details and game version
Version - Latest on develop
[2017-02-15_20-05-45.zip](https://github.com/MovingBlocks/Terasology/files/777355/2017-02-15_20-05-45.zip)

### Computer details
Nvidia gtx 960m (Latest drivers, updated 2 days back)
8gb ram
Windows 10

**Comment by jellysnake** [comment] 2017-02-15 23:14
Hmm, so I'm not being able to reproduce this.
Can you try undoing your CrashReporter changes and running gradlew idea before attempting to build?

**Comment by emanuele3d** [comment] 2017-02-15 23:19
It's certainly unusual to see a problem of this kind on a system with such a modern graphics card. I hope it won't be the start of a trend.

**Comment by Cervator** [comment] 2017-02-16 02:10
Try upgrading the driver again. A new one with including a hotfix that previously left MC broken was released *today* - so even two days old could be a problem :D

Other than that we're doing a fair bit of shuffling around in rendering land, it may take a few more releases before we switch from moving fast and breaking things to truly stabilizing again :-)

**Comment by zeokav** [comment] 2017-02-16 12:24
Alright, clean installing the newest driver did it for me. It was a problem with NVidia's 378.49 drivers then, I'm guessing. 
Yay nothing's broken!

**Comment by emanuele3d** [comment] 2017-02-16 13:12
Pheeew. :relieved:

**Comment by Malanius** [comment] 2017-02-16 17:26
Had the same issue. It was really caused by nVidia drivers, waited for the newer one, as this is not the first time nVidia drivers broken something badly...

**Comment by Cervator** [comment] 2017-02-17 07:01
Kinda glad I didn't update! Saw the news about the MC breakage + hot fix and was waiting to see this one released.

Closing as "fixed" - huzzah!

**Closed by Cervator** 2017-02-17 07:01 UTC
