### ISSUE TITLE
Volumetric Fog broken

### ISSUE THREAD

**Issue by Translator5** [MovingBlocks/Terasology#2246] opened 2016-03-20 00:32 UTC
Terasology Alpha 64
Linux Mint 17-3
Java JDK 8
Installed using the launcher

I played a bit with the graphics, and recognized the following issues.
If you open the graphic-setting while in a server/map, your unpicked/dropped items will not show any texture.
The way to fix is to reload the map, reconnect to the server.
[Screenshot](http://s7.postimg.org/e2ts2bqix/Terasology_160320010345_1920x1080.png)
[Mirror2](http://postimg.org/image/u12hsgkqv/full/)

If you allow Volumetric Fog, the following happens, even after game restart it do not work.
[Screenshot](http://s27.postimg.org/m6g92wcpt/Terasology_160320012657_1920x1080.png)
[Mirror2](http://postimg.org/image/h7sqod8wv/ef2ca543/)
##

**Comment by emanuele3d** [comment] 2016-03-20 22:09
The issue with the untextured objects seems to be the same as in #966.

The issue with the Volumetric Fog is a new one, as until recently we had no graphic option for Volumetric Fog.

@Translator5: can you please:
* add your screenshot in a comment to issue #966.
* edit this issue, title included so that it's only about the Volumetric Fog problem.

@Cervator: please assign this issue to me for the time being. As I'm not going to work on it for a while at least, what do you think we should do? Remove the Volumetric Fog option altogether or leave there but perhaps label it as broken?

**Comment by skaldarnar** [comment] 2016-03-21 16:43
@emanuele3d assigned the issue to you. Are you able to reproduce the issue/track it down to the option?

**Comment by emanuele3d** [comment] 2016-03-21 21:50
@skaldarnar, I am able to reproduce. I'm not sure what you mean with "track it down to the option". =?

**Comment by skaldarnar** [comment] 2016-03-21 22:38
eh, I shouldn't write comments when in a hurry :laughing: my thought was to find the spot where it breaks, i.e., why does the new option break the game. Here's a reference to the PR: https://github.com/MovingBlocks/Terasology/pull/2211

**Comment by emanuele3d** [comment] 2016-03-22 22:51
By my understanding @tdgunes has enabled the turning on/off of a setting he found in the Rendering config. However, this doesn't mean the underlying effect, volumetric fog, is currently functional. Hence my question: assuming it can't be easily fixed, do we leave the option there, perhaps labeling it as "broken" or do we hide it from the video settings?

**Comment by Cervator** [comment] 2016-03-23 01:54
Well, the option is already in the experimental section and defaulted to off, so I'm not losing sleep over it :-) We still even have an Oculus Rift toggle in there which has been broken for ages.

I think we should keep the options but if something is broken 100% maybe we should ghost out the checkbox to indicate "broken" entirely? Although I'm not sure we can inactivate a checkbox?

**Comment by pollend** [comment] 2016-03-26 17:37
@Cervator  I believe I resolve this in pull #2256

**Comment by Translator5** [comment] 2016-03-30 18:13
@pollend the volumetric fog is still an issue in dev. build #1.681 alpha 2016-03-30T05:13:51Z!
The dropped-items are fixed!

**Comment by Cervator** [comment] 2016-03-30 19:31
@Translator5 I think we should keep this open as volumetric fog is indeed broken. The other fix was covered by #966 which is now closed. I'll rename this a bit for clarity

I've also submitted #2268 to get the UI support for disabling the volumetric fog checkbox until it is working again.

**Closed** 2018-03-20 22:23 UTC
Labels: Rendering
