### ISSUE TITLE
Low Resolution Bugs (GCI Arjan Guglani)

### ISSUE THREAD

**Issue by Arjanguglani** [MovingBlocks/Terasology#2649] opened 2016-12-08 03:09 UTC
1.
<img width="1143" alt="screen shot 2016-12-07 at 9 55 16 pm" src="https://cloud.githubusercontent.com/assets/11148088/20996028/ac2d9fc8-bcc8-11e6-9fd9-efd523bc335a.png">

2.
<img width="1023" alt="screen shot 2016-12-07 at 9 56 59 pm" src="https://cloud.githubusercontent.com/assets/11148088/20996027/ac2ae9a4-bcc8-11e6-861b-0dd99c39f200.png">

3.
<img width="1021" alt="screen shot 2016-12-07 at 9 57 26 pm" src="https://cloud.githubusercontent.com/assets/11148088/20996026/ac29b39a-bcc8-11e6-8a17-91e34cd099d8.png">

### What you were trying to do / How to reproduce

1. Creating a single player game.

2. Retrieving the seed while creating a multi player game.

3. Adding modules to a multiplayer game.

### What actually happened

1. The play and back buttons came over text.

2. The attributes modifier pane was so small it was virtually unusable.

3. The attributes modifier pane was so small it was virtually unusable.

### Log details and game version

#70 alpha 2016-11-28T06:33:33Z 

### Computer details
2015 Macbook Pro (13 inch) running 1024 X 768 Resolution

**Comment by rzats** [comment] 2016-12-08 11:29
Thanks for the detailed report 🙂

The first issue is something that was actually fixed fairly recently (#2638) - can you update your workspace to the latest version and try testing it again?

**Comment by skaldarnar** [comment] 2023-07-02 16:51
Duplicate of #2585.

**Closed by skaldarnar** 2023-07-02 16:51 UTC
Labels: Type: Bug, Topic: UI/UX
