### ISSUE TITLE
Water disappears when a torch is placed

### ISSUE THREAD

**Issue by meetcshah19** [MovingBlocks/Terasology#3861] opened 2020-03-19 14:34 UTC
What you were trying to do

Place a torch in a place with water ( 1 block height ).

What actually happened

The torch got placed and water disappeared!

**Comment by Cervator** [comment] 2020-03-20 01:34
So this is sort of a quirky one. It isn't really a bug - the engine is working exactly as intended, but the intention may be weird. `Water.block` has `"replacementAllowed": true,` in it which means you can replace it with any other block. Normally that's stuff like dirt or other solid blocks, but the engine doesn't distinguish.

At the engine / Core level I don't think this is something we'd want to complicate, but it _is_ something a bigger gameplay template could change. For instance the Throughout The Ages gameplay (which is sadly unmaintained and barely works) did an override on most blocks to where they don't drop _as_ blocks, so you can't get easy building materials (it is meant as a "hard mode" sort of setting). They drop as items instead, which in some cases (like clay -> bricks -> brick walls) can then be worked into a refined block again.

Really, IMHO, it should likewise be up to some gameplay setting to give more direction to water - literally in the case of FlowingLiquids, for example, which makes water flow, which again isn't a feature in the bare engine / Core series :-)

So I'm going to close this in favor of a future in which somebody makes water more meaningful. Wink ;-)

**Closed by Cervator** 2020-03-20 01:34 UTC
