### ISSUE TITLE
Water reflection only works at sea level (y=32)

### ISSUE THREAD

**Issue by Loonride** [MovingBlocks/Terasology#3660] opened 2019-04-06 03:36 UTC
I wanted to get this problem documented, as it could potentially be improved after shader refactoring.

### What you were trying to do

See proper reflections in water at any height.

### What actually happened

Water reflections rely on the water being at sea level. When it is not, the fbo is drawn to from the wrong camera perspective. Here's an image of what it looks like at around y=64, with all other shader effects for the water stripped away:

![Terasology-190330235244-1362x706](https://user-images.githubusercontent.com/22580625/55664408-aeed4c00-57f2-11e9-8c2c-63606b071ab7.png)

This cannot simply be fixed by changing the camera perspective, because if you have two water blocks at different heights next to one another, the reflection of one will look right, and the other will look wrong. I think the solution would be to determine the reflection color in the same shader where the water surface is actually drawn, rather than drawing it to an fbo and sampling from it later.

### How to reproduce

- Take out all water effects besides the `reflectionColor` in the chunk fragment shader
- use the `give water` command in the game
- place water at a height far away from y=32

**Comment by 4Denthusiast** [comment] 2020-05-23 17:13
This is a duplicate of #1476.

**Comment by skaldarnar** [comment] 2020-05-23 22:14
Closing as duplicate (thanks for spotting @4Denthusiast)

**Closed by skaldarnar** 2020-05-23 22:14 UTC
