### ISSUE TITLE
Translation keys for graphic presets seem to not be in use

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2207] opened 2016-03-05 22:01 UTC
### What you were trying to do

See the graphic presets like "Uber" and "Insane" get translated into other languages - we have the values in the language files.

### What actually happened

I always see English values in the graphics present drop-down, regardless of what language is selected.

Somewhat related to #2028 as we probably should clarify the actual names then re-translate where needed.

**Comment by rzats** [comment] 2016-03-06 21:07
This is caused by the game not handling translations at all when populating dropdowns in video settings. For example, when populating `videoQuality` ([link](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java#L69)) the game grabs a list of `Preset` enums ([link](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/Preset.java)) with hardcoded English value strings and does nothing else. 

Fixing this would involve:

- [ ] Modifying the strings in enums so that they reflect the keys in .lang files more accurately. In the above example, `MINIMAL("minimal")` should be changed to [MINIMAL("video-preset-minimal")](url) because that's the key for that particular option in the resource files - same with all the other options.

- [ ] At some point piping these enum strings through a TranslationSystem to resolve them into translations.

**Comment by Margretor** [comment] 2016-03-07 01:05
I would like to investigate this issue

**Comment by indianajohn** [comment] 2016-07-11 07:10
Realized that https://github.com/MovingBlocks/Terasology/pull/2226/files is this and more. Feel free to close this if you'd like; I'm really just poking around the code base and getting familiar with things.

**Closed** 2016-07-22 05:10 UTC
Labels: Bite-size, Contributor-friendly, in progress, UI
