### ISSUE TITLE
Terasology Crashing on Alt+Tab

### ISSUE THREAD

**Issue by CsyTheArgonaut** [MovingBlocks/Terasology#4974] opened 2021-12-06 10:04 UTC
https://pastebin.com/P56sEmrY
Sorry for not posting this here, I put it in the pastebin!
It was on Terasology version 5.2.0, started from launcher, gameplay was JoshariasSurvival with no additional modules and I was crashing shortly after hitting Alt+Tab after having spawned but before everything loaded. I was playing in fullscreen mode is thats relevant?

**Comment by jdrueckert** [comment] 2022-01-04 18:34
Duplicate of https://github.com/MovingBlocks/Terasology/issues/4575

**Closed by jdrueckert** 2022-01-04 18:34 UTC
Labels: Type: Bug, Status: Needs Investigation, Topic: Stabilization, Category: Crash, Topic: Concurrency
