### ISSUE TITLE
Problems with UI's on 1024x768 screen

### ISSUE THREAD

**Issue by TheJYKoder** [MovingBlocks/Terasology#2680] opened 2016-12-18 23:26 UTC
1.
![onlineplayersoverlay](https://cloud.githubusercontent.com/assets/17117557/21296975/605ff6ce-c545-11e6-9cb3-0d2100255d63.PNG)

2.
![migtestscreen](https://cloud.githubusercontent.com/assets/17117557/21296987/78803624-c545-11e6-8fa1-ec1c4adc8738.PNG)

3.
![console](https://cloud.githubusercontent.com/assets/17117557/21296988/7a3c61a4-c545-11e6-84e6-8538fc82b683.PNG)

4.
![waitpopup](https://cloud.githubusercontent.com/assets/17117557/21296989/7bd0589a-c545-11e6-9c43-5cf39f84b0b2.PNG)

### What you were trying to do
* Image 1: Open the 'onlinePlayersOverlay' ui
* Image 2: Open the 'migTestScreen' ui
* Image 3: Type in Commands to the Console
* Image 4: Open the 'waitPopup' ui

### What actually happened
* Image 1: The "g" in 'Junyoung' got cut off
* Image 2: The 'UIBox' of the first column has overflowing text
* Image 3: The "g" was cut off when I was typing
* Image 4: Despite clicking 'cancel', the UI would not go away.
### How to reproduce

* Image 1: Hit 'F1' and type 'showScreen onlinePlayersOverlay' (be sure that your name has the letter 'g',  'j', or'y').
* Image 2: Hit 'F1' and type 'showScreen migTestScreen' 
* Image 3: Hit 'F1' and type something that has the letter 'g',  'j', or'y'.
* Image 4: Hit 'F1' and type 'showScreen waitPopup' and then try to to click 'cancel'

### Log details and game version
Game Version: Alpha

### Computer details
Dell XPS 2720 set to resolution of 1024x768

**Comment by Metatricity** [comment] 2016-12-20 20:55
Odd. I've never experienced this before and I ran on a 1024x768 screen, however it was laggy since it was Dell Precision 670 WorkStation server :/

Not exactly your gaming rig.

**Comment by acterhd** [comment] 2017-01-11 22:44
Simular issue... 
https://github.com/MovingBlocks/Terasology/issues/2716

**Comment by skaldarnar** [comment] 2023-07-02 16:52
Duplicate of #2585.

**Closed by skaldarnar** 2023-07-02 16:52 UTC
Labels: Topic: UI/UX
