### ISSUE TITLE
Low Resolution Bugs

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/Terasology#2655] opened 2016-12-10 13:09 UTC
![capture](https://cloud.githubusercontent.com/assets/4402697/21073535/c197c95e-bf13-11e6-91ec-2a5e2ca2d444.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4402697/21073537/c1a42776-bf13-11e6-927a-b38187e6014c.PNG)
![capture3](https://cloud.githubusercontent.com/assets/4402697/21073536/c199e73e-bf13-11e6-9f7b-f91b19f6874f.PNG)

### What you were trying to do
1. Edit the behaviour tree
2. Select a drop down item in the NUI skin editor.
3. Select a drop down item in the NUI screen editor 

### What actually happened
1. Some text are out of the box, some boxes on the right are out of the screen.
2. Some items from the drop down are extremely hard to click due to it being covered.
3. Some items from the drop down are extremely hard to click due to it being covered.

### How to reproduce

1. Access the behaviour tree in low resolution.
2. Access the NUI skin editor in low resolution.
3. Access the NUI screen editor in low resolution.

### Log details and game version
#2647 Alpha

### Computer details
Lenovo Y500 | Windows 10 64-Bit
Resolution (1024x768)

**Comment by WH1CRT** [comment] 2016-12-10 16:03
I also replicated this issue and have experienced the same problem.

Computer Details
Windows 7 Premium 64-Bit 
Resolution (1024x768)

- Will

**Comment by skaldarnar** [comment] 2023-07-02 16:51
Duplicate of #2585.

**Closed by skaldarnar** 2023-07-02 16:51 UTC
Labels: Type: Bug, Topic: UI/UX
