### ISSUE TITLE
SkyBox rendering issues

### ISSUE THREAD

**Issue by modmuss50** [MovingBlocks/Terasology#2490] opened 2016-09-26 19:33 UTC
### What you were trying to do

I was trying to play the game
### What actually happened

I noticed very quickly that something wasnt right with the skybox, best to see in the following screen shot and video: 

![alt text](https://modmuss50.me/shots/2016-09-26_20-06-17.jpg)
![alt text](https://modmuss50.me/shots/2016-09-26_20-28-19.png)

The video can be watched here:
https://modmuss50.me/shots/2016-09-26_20-13-24.mp4
### How to reproduce
- Open the game to the main menu
- Maximize the game window
- Open any world in the game and see the issue
### Log details and game version

Game version from main menu: 1801 2016-09-20

Not sure how to get the log, ask I can can provide at a later date.
### Computer details

Intel i7 4790k
AMD 270x graphics card
8GB ram

Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
##

**Comment by emanuele3d** [comment] 2016-09-26 22:29
@modmuss50 : thank you for the report. 

I was able to reproduce the problem at least once, although for some reason the same steps didn't produce the same problem again, even restarting the application from scratch.

I will be working on the parts of the rendering engine dealing with the sky over the next week or so if all goes according to plan. A quick inspection of the relevant code already reveals some possible issues.

Hopefully I will be able to solve the issue relatively soon. Just do not hold your breath because we all do this in our free time.

Meanwhile, can you confirm the issue does not occur if, say, you switch from fullscreen mode to windowed and viceversa? Or by manually resizing the window?

**Comment by modmuss50** [comment] 2016-09-27 06:50
Ok, I will go through some stages:

* Open game, load world, all is fine.
* Maximize window while world is loaded, all is fine.
* Enter fullscreen, all is fine
* Exit fullscreen and the world to main menu - **Window is no longer resizeable**
* Restart game, maximize at main menu, all is fine the world.

So I cannot get it to do it again for some reason, only thing to note is the window cannot be resized after exiting full screen. I will let you know if I encounter it again.

**Comment by Cervator** [comment] 2017-03-26 22:54
I believe this is now fixed enough by #2844 to be closed :-)

Window not being resizable at all after returning from full screen is s different issue and is covered by #2532 (not fixed yet)

**Closed by Cervator** 2017-03-26 22:54 UTC
Labels: Bug, Rendering
