### ISSUE TITLE
Crash while pressing F12

### ISSUE THREAD

**Issue by Morovaille** [MovingBlocks/Terasology#1933] opened 2015-09-16 17:34 UTC
http://pastebin.com/bxGuiDZ4

**Comment by Cervator** [comment] 2015-09-16 18:21
Hi @Morovaille - getting an error that the paste has been removed?

I know from the past if you attempt to take large screenshots with low memory allocation that can cause a crash. Are you running in a high screen resolution with the game launched with a 32-bit Java by chance? Or just on a system with low overall system memory?

**Comment by Morovaille** [comment] 2015-09-16 19:00
Hi !

Sorry for the deleted pastebin, but I just paste the link given in the crash report tool.

I found this in the log : 
19:32:39.275 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.opengl.LwjglRenderingProcess.takeScreenshot(LwjglRenderingProcess.java:211) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.logic.players.MenuControlSystem.onKeyDown(MenuControlSystem.java:82) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.logic.players.MenuControlSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:57, master, 57, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.input.InputSystem.sendKeyEvent(InputSystem.java:380) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:329) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.input.InputSystem.update(InputSystem.java:212) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:197) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55) ~[engine-0.54.1.jar:57, master, 57, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:420) ~[engine-0.54.1.jar:57, origin/master, 57]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:366) ~[engine-0.54.1.jar:57, origin/master, 57]
	at org.terasology.engine.Terasology.main(Terasology.java:153) [Terasology.jar:57, origin/master, 57]
19:32:39.277 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...

I tried to make the bug happen again but it did not.

Actually I launched the game on a full HD screen and java is limited to 2Go memory, so perhaps it was the reason of the bug.

Please tell me if I can help more on this case...

**Comment by Cervator** [comment] 2015-09-16 19:03
Oh maybe the pastebin upload is still wonky. We really need to look at that :/

It is https://github.com/MovingBlocks/CrashReporter/issues/16 for reference - pinging @msteiger for sometime :-)

The error may well be just above the part you pasted. But yeah it is right in the spot where I'd suspect memory first try.

There should be some options related to the size of screenshots that may help, or you could just feed Java more memory if you have it available :-)

If you can post the full log (on pastebin or elsewhere) we might be able to spot if there is a separate issue, but if it is just memory there are workarounds for that.

**Comment by Morovaille** [comment] 2015-09-16 19:13
Here is the complete log : http://pastebin.com/i6hr8Zmu

Yes I can feed java more memory, this is not a problem. I just wanted to help by reporting this crash :)

**Comment by Cervator** [comment] 2015-09-16 19:33
You did the right thing and it is appreciated! :-)

And actually hmm, the log doesn't seem to indicate a memory issue anywhere. More likely to be a screenshot config issue. The following line caused a null pointer exception:

`overwriteRtWidth = renderingConfig.getScreenshotSize().getWidth(Display.getWidth());`

I can't replicate it though, works fine on my system both as a regular window and in full screen. How high is the resolution of your HD display and were you running in full screen? Did anything change in your setup after you crashed once?

Maybe the config.cfg file was bad and got set with valid values after the crash.

**Comment by Morovaille** [comment] 2015-09-16 19:59
I play on a 1920 x 1080 screen and I did not changed the resolution configuration. The game was in full screen. It *seems* nothing changed after relaunching.

I tried to lauch the game after deleting the confing.cfg, but the game did not crash when I took a screenshot...

**Comment by Cervator** [comment] 2015-09-16 20:24
Oh well. It is probably some obscure sequence of events that can lead to it then. Likely a legit bug but hard to reproduce so hard to do anything about.

Since you can take screenshots no problem now I'll go ahead and close this, but we'll have it in issue history should somebody else hit it later. Likewise if you trigger it again and find any additional details please report back!

And thanks again for the report and for playing. Hope you can have some fun and stick around to watch the game grow and improve :-)

**Closed by Cervator** 2015-09-16 20:24 UTC
Labels: Support
