### ISSUE TITLE
Black screen on changing from windowed mode to fullscreen when playing

### ISSUE THREAD

**Issue by zeokav** [MovingBlocks/Terasology#2659] opened 2016-12-11 05:31 UTC
### What you were trying to do
Change a few video settings when the game was running. Switching from windowed to full screen causes the game to display a black screen with nothing else on it.
### What actually happened
As soon as I switch to full screen mode, everything disappears. However, the game doesn't really crash - it's just a black screen. I can still see the game being saved. I am attaching a copy of the logs. Search for '!!!' in Terasology-Game_2 to jump directly to the part where the black screen issue happened.

### How to reproduce

* Step 1 Launch the game in windowed mode, and start playing (load or create a new game)
* Step 2 Open video settings and change from windowed to full screen
* Step 3 The darkness.

### Log details and game version
Version - built from the latest sources.
Logs - 
[2016-12-11_10-28-22.zip](https://github.com/MovingBlocks/Terasology/files/644241/2016-12-11_10-28-22.zip)

### Computer details
8 GB RAM, 
i7-6700HQ 2.6 GHz
Nvidia GTX 960m 4GB VRAM
Windows 10

Edit: Could not get a screenshot of the black screen because it doesn't work for some reason. (But trust me, it's just a black screen with nothing on it.)

**Comment by emanuele3d** [comment] 2016-12-11 13:33
Thank you for the report. We are aware of issues related to any kind of display-resizing, i.e. from full screen to window, viceversa and even just interactively resizing the window. I.e. see #2528. At this stage I believe this problem is connected to those issues. As soon as I have the time this will get fixed.

Meanwhile, the simple workaround is to reload the game or, in the worst case scenario, restart Terasology. 

Apologies for the inconvenience.

**Comment by zeokav** [comment] 2016-12-11 13:57
@emanuele3d Let me know if you need some minor assistance, I'll be happy to help. 😃

**Comment by emanuele3d** [comment] 2016-12-11 14:41
@zeokav: thank you for the offer. Unfortunately this problem has to do with FrameBufferObjects (FBOs) and their regeneration anytime the display is resized. This makes this issue a moderately difficult one to understand even though it might not be overly difficult to fix: it's probably a hard to find/(potentially) easy to fix kind of thing. So, I wouldn't consider it "minor". But of course you'd be welcome to try. =)

You'd have to look into the classes BindFBO, SetViewportToSizeOf and probably also in DisplayResolutionDependentFBOs and DefaultDynamicFBOs. I suspect the problem is somewhere there.

**Comment by zeokav** [comment] 2016-12-13 13:28
@emanuele3d I don't know if this is of any help, but I kinda played with the code around, and figured out that in DisplayResolutionDependentFBOs.update(), the predicate inside the if statement becomes true when the window size changes. When I commented out all the 4 methods that it calls, disposeAllFBOs(), createFBOs(), updateDefaultFBOs(), notifySubscribers(), the game doesn't crash on changing resolution, but instead the stuff that's drawn is small in size with black sides, naturally. I'm guessing it's one of those methods causing the problem then?

**Comment by emanuele3d** [comment] 2016-12-13 15:30
FrameBuffers are chunks of memory that the GPU uses to store, for example, images. These could be images used as input to some rendering processes and they could be images that get displayed on screen.

When the window is resized the size of most FBOs used by Terasology needs to match the size of the window. But as FBOs in GPU memory cannot be really resized, the existing FBOs are simply deleted and re-created. That's what the update() method does.

I suspect the problems arise from the so-called "DefaultFBOs". They have been an headache since they were implemented. Can you investigate in that direction if you have time?

**Comment by zeokav** [comment] 2016-12-14 12:47
@emanuele3d I tried going through the code but I don't think I understand everything that's happening there. Why are the default FBOs updated if you're deleting and recreating all the FBOs anyway on resolution change? Shouldn't this delete and create the default FBOs as well?

**Comment by Cervator** [comment] 2016-12-21 05:41
@emanuele3d: bump :-)

**Comment by emanuele3d** [comment] 2016-12-21 14:06
Sorry for the delay @zeokav and thank you for the bump @Cervator.

It is true that all FBOs are deleted and recreated on resize. However, the call updateDefaultFBOs only updates the references to the FBOs contained in the DefaultDynamicFBO objects, retrievable via their getFbo() method. 

DefaultDynamicFBO is an enum class that acts as a wrapper on top of the actual FBOs, as a convenient way to obtain FBOs that are present by default in the rendering engine. At least that was the thinking. Unfortunately it made the code much less straightforward and I plan to eliminate them. In fact I already tried but broke the renderer. For this reason I'm first refactoring all nodes first, to make sure they are as lean as they can be, so that it's easier to understand where these issues come from and what nodes it impacts.

Does this answer your question?

**Comment by zeokav** [comment] 2016-12-27 18:17
@emanuele3d Yep, all clear. I was confused about the references part. Since you're already working on restructuring the whole thing, I'll contribute elsewhere and come back later if another bug pops up!

**Comment by Cervator** [comment] 2017-03-26 22:45
Closing as fixed by #2844!

**Closed by Cervator** 2017-03-26 22:45 UTC
Labels: Bug, Rendering
