### ISSUE TITLE
crash when "back into menu" in a game

### ISSUE THREAD

**Issue by XAOc57** [MovingBlocks/Terasology#1791] opened 2015-06-24 14:58 UTC
http://pastebin.com/G1zUZHUG

P.S. I am sorry for my mistakes in registration crash report, i'm no developer.

**Comment by Cervator** [comment] 2015-06-24 15:20
Thanks for the report, this is fine :-)

I see the graphic settings are being updated, did you by chance change them during playing while in the world? @emanuele3d might have some thoughts there on whether the logs indicate a problem updating the graphic settings that could explain the crash.

Do you by chance have another log file or two? This looks like the game log, you may also have a menu or even an init log.

Did the crash happen when you went to the main menu or attempted to exit the game entirely?

**Comment by XAOc57** [comment] 2015-06-24 15:44
All logs generated by the game. https://yadi.sk/d/AB57-TuqhTJkH
Yes, the graphics settings have been changes in the game.
Change: View distanse: Ultra > Far
I think there is the same, but slightly under other conditions but with the same setting View Distanse: https://github.com/MovingBlocks/Terasology/issues/1792

**Comment by Cervator** [comment] 2015-06-24 15:47
Much appreciated, we can test that sometime, just give us a little while :-)

No need for a second issue report if it is the same issue, we can sort it out and see if it eventually results in two bugs or not

Thanks again for the details!

**Comment by emanuele3d** [comment] 2015-06-24 21:51
Issue noted. Sounds familiar. I wouldn't be suprised if by the time I dealt with what's left of the LwjglRenderingProcess the problem is fixed. Could get fixed over the next couple of weeks. I need to check the logs for the actual error though. I do not have the time right now. Assign it to me for the time being @Cervator, please.

**Comment by Cervator** [comment] 2015-06-24 21:55
@emanuele3d: Much appreciated!

@XAOc57: Hang in there, help is on the way :D

**Comment by Cervator** [comment] 2015-07-28 02:33
@XAOc57 - bump! This should now be resolved :-)

Fix is in the release presently being prepared + in latest dev build

**Closed by Cervator** 2015-07-28 02:33 UTC
Labels: 3D-Wizardry, Support
