### ISSUE TITLE
Follow-ups after JOML adoption

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3832] opened 2020-02-16 03:10 UTC
With #3811 we embark on the journey to adopt JOML instead of our aging TeraMath library. It won't be without bruises for such a major change, however! Creating this issue to capture some future todos to follow back up on, either when somebody is able to dig in or after the final engine PR finishes the journey (and likely rolls into module land). I'm just noting a few impressions here, @pollend would probably be better at detailing them over time 👍 

## Backlog

- [x] https://github.com/Terasology/Minesweeper/pull/20

## Drafts

- [x] Draft: feat(JOML): migrate and clean up code (https://github.com/Terasology/SegmentedPaths/pull/15)
- [ ] [19 PRs on JOML primitives](https://github.com/search?q=org%3ATerasology+is%3Apr+is%3Aopen+joml+primatives&type=Issues) (to be migrated to use `joml-geometry`) 

## Done

<details>
<summary>Details</summary>

- [x] https://github.com/MovingBlocks/Terasology/pull/4404
- [x] https://github.com/Terasology/CoreRendering/pull/26
- [x] https://github.com/Terasology/Inventory/pull/31
- [x] https://github.com/Terasology/WorkstationCrafting/pull/22
- [x] https://github.com/Terasology/WeatherManager/pull/20
- [x] https://github.com/Terasology/Caves/pull/14
- [x] https://github.com/Terasology/SurfaceFacets/pull/9
- [x] https://github.com/Terasology/AnotherWorld/pull/20
- [x] https://github.com/Terasology/AdditionalRails/pull/44
- [x] https://github.com/Terasology/BiomesAPI/pull/9
- [x] https://github.com/Terasology/ClimateConditions/pull/44
- [x] https://github.com/Terasology/Climbables/pull/5
- [x] https://github.com/Terasology/CustomOreGen/pull/10
- [x] https://github.com/Terasology/Equipment/pull/131
- [x] https://github.com/Terasology/Fluid/pull/29
- [x] feat(JOML): migrate block networks (https://github.com/Terasology/BlockNetwork/pull/15)
- [x] feat(JOML): migrate chunkview and tests cases (https://github.com/MovingBlocks/Terasology/pull/4335)
- [x] ~~WIP: feat(JOML): migrate aabb for joml mesh (https://github.com/MovingBlocks/Terasology/pull/4190)~~
- [x] ~~WIP: feat(JOML): Migrate ChunkProvider (https://github.com/MovingBlocks/Terasology/pull/4072)~~
- [x] feat(JOML): migrate BaceFacet2d for BlockArea (https://github.com/MovingBlocks/Terasology/pull/4364) (+ dependent module PRs)
- [x] feat(JOML): remove refrences to JOMLUtil (https://github.com/Terasology/Projectile/pull/14)
- [x] feat(JOML): migrate DefenceWorldManager (https://github.com/Terasology/GooeyDefence/pull/51)
- [x] feat(JOML): migrate CaveFacet, CaveFacetProvider, CaveRasterizer, CaveToDensityProvider, LavaLevelFacet, InternoClientSystem (https://github.com/Terasology/Inferno/pull/17)
- [x] feat(JOML): migrate BouncySystem (https://github.com/Terasology/FunnyBlocks/pull/22)
- [x] https://github.com/Terasology/WorkstationCrafting/pull/21
- [x] https://github.com/Terasology/WorkstationCrafting/pull/20

- [x] https://github.com/Terasology/Scenario/pull/48
- [x] ~~feat(joml): align Region related classes (https://github.com/Terasology/StructureTemplates/pull/46)~~
- [x] https://github.com/Terasology/Minesweeper/pull/19
- [x] https://github.com/Terasology/WeatherManager/pull/18
- [x] https://github.com/Terasology/LightAndShadow/pull/181
- [x] https://github.com/Terasology/IRLCorp/pull/30
- [x] https://github.com/Terasology/Behaviors/pull/53/ (plus dependent module PRs)
- [x] feat(joml): migrate FallingBlocks to JOML (https://github.com/Terasology/FallingBlocks/pull/1)
- [x] feat(joml): joml-ify TreeGeneratorLSystem; adjust tree extents in tests and facets  (https://github.com/Terasology/CoreWorlds/pull/17)
- [x] feat(JOML): align `PlaySoundAction` with audio jomlification (https://github.com/Terasology/Behaviors/pull/50)
- [x] feat(JOML): migrate `AudioManager (https://github.com/MovingBlocks/Terasology/pull/4275)
- [x] feat(JOML): migrate block selection component (https://github.com/MovingBlocks/Terasology/pull/4263)
- [x] feat(JOML): migrate monitoring (https://github.com/MovingBlocks/Terasology/pull/4260)
- [x] feat(JOML): migrate `InputSystem` and events (https://github.com/MovingBlocks/Terasology/pull/4259/)
- [x] feat(JOML): migrate core commands (https://github.com/MovingBlocks/Terasology/pull/4251)
- [x] feat(JOML): migrate LocalPlayerSystem (https://github.com/MovingBlocks/Terasology/pull/4249)
- [x] feat(JOML): migrate card system (https://github.com/Terasology/LightAndShadow/pull/170)
- [x] feat(JOML): migrate direction (https://github.com/Terasology/ItemPipes/pull/24)
- [x] changes from bullet physics conversion - JOML (https://github.com/Terasology/AdditionalRails/pull/36)
- [x] changes from bullet physics conversion - JOML (https://github.com/Terasology/Rails/pull/51)
- [x] JOML-conversion compatibility fix for Terasology PR #3919. (https://github.com/Terasology/KComputers/pull/1)
- [x] changes from bullet physics conversion - JOML (https://github.com/Terasology/Alchemy/pull/9)
- [x] changes from bullet physics conversion - JOML (https://github.com/Terasology/AdvancedRails/pull/5)
- [x] feat(JOML): tweak for simple farming (https://github.com/Terasology/AdditionalRails/pull/43)
- [x] feat(JOML): minor tweak from simplefarming (https://github.com/Terasology/MetalRenegades/pull/100)
- [x] general cleanup and migration to JOML mainly with support methods (https://github.com/Terasology/Potions/pull/64)
- [x] feat(JOML): migrate and clone up code and update copyright (https://github.com/Terasology/WildAnimals/pull/63)
- [x] feat(JOML): migrate and clean up (https://github.com/Terasology/StructureTemplates/pull/45)
- [x] feat(JOML): general cleanup and migration of code for joml (https://github.com/Terasology/Projectile/pull/13)
- [x] feat(JOML): cleanup and migrate code to joml (https://github.com/Terasology/AdventureAssets/pull/31)
- [x] feat(JOML): migrate SimpleFarming (https://github.com/Terasology/SimpleFarming/pull/101)
- [x] feat(JOML): migrate player factory (https://github.com/MovingBlocks/Terasology/pull/4205)
- [x] feat(JOML): migrate ChunkMath#getChunkRegionAroundWorldPos (https://github.com/MovingBlocks/Terasology/pull/4204)
- [x] feat(JOML): migrate storage transaction (https://github.com/MovingBlocks/Terasology/pull/4203)
- [x] feat(JOML): migrate BlockItemSystem and Physics#scanArea (https://github.com/MovingBlocks/Terasology/pull/4193)
- [x] feat(JOML): migrate FirstPeronHeldItem/Mount/Transform Component
 (https://github.com/MovingBlocks/Terasology/pull/4178)
- [x] feat(JOML): migrate `GooKeeper` (https://github.com/Terasology/GooKeeper/pull/25)
- [x] feat(JOML): migrate NetClient (https://github.com/MovingBlocks/Terasology/pull/4183)
- [x] feat(JOML): migrate CharacterMovmentComponent (https://github.com/MovingBlocks/Terasology/pull/4177)
- [x] feat(JOML): migrate physic event ChangeVelocity/Force,Impulse Event (https://github.com/MovingBlocks/Terasology/pull/4176)
- [x] feat(JOML): migrate action event(https://github.com/MovingBlocks/Terasology/pull/4172)
- [x] feat(JOML): migrate random (https://github.com/MovingBlocks/Terasology/pull/4167)
- [x] feat(JOML): migrate DistanceComparator (https://github.com/MovingBlocks/Terasology/pull/4165)
- [x] feat(JOML): migrate block (https://github.com/MovingBlocks/Terasology/pull/4164)
- [x] feat(JOML): remove use of JOMLUtil for #getBlock (https://github.com/MovingBlocks/Terasology/pull/4163)
- [x] feat(JOML): migrate LocalPlayer and correct Direction (https://github.com/MovingBlocks/Terasology/pull/4162)
- [x] feat(JOML): migrate target system (https://github.com/Terasology/WorldlyTooltip/pull/13)
- [x] feat(JOML): migrate target system (https://github.com/MovingBlocks/Terasology/pull/4161)
- [x] feat(JOML): Migrate JOML for MultiConnectFamily and UpdateWithNeighboursFamily (https://github.com/MovingBlocks/Terasology/pull/4069)
- [x] add RectangularRegion to replace Rect2i (https://github.com/MovingBlocks/Terasology/pull/4050)
- [x] feat(JOML): add BlockRegion#center (https://github.com/MovingBlocks/Terasology/pull/4159)
- [x] feat(JOML): add orientation for Rotation (https://github.com/MovingBlocks/Terasology/pull/4168)
- [x] Expose JOML as a package to modules (https://github.com/MovingBlocks/Terasology/pull/3833)
- [x] Feature/joml (https://github.com/MovingBlocks/Terasology/pull/3811)
- [x] converted terasology vector2i to joml vector2i for font (https://github.com/MovingBlocks/Terasology/pull/3866)
- [x] added serilization compatibility for joml along with a basic test for (https://github.com/MovingBlocks/Terasology/pull/3869)
- [x] bumped version of joml and resolved direction of lightshafts (https://github.com/MovingBlocks/Terasology/pull/3885)
- [x] feat(JOML): Migrate methods of WorldProvider (https://github.com/MovingBlocks/Terasology/pull/3899)
- [x] partial port of kinematicCharacterMover (https://github.com/MovingBlocks/Terasology/pull/3902)
- [x] JOML migration for AudioManager (https://github.com/MovingBlocks/Terasology/pull/3908)
- [x] eat(JOML): Migrate PlayerFactory (https://github.com/MovingBlocks/Terasology/pull/3912)
- [x] feat(JOML): Migrate Particle System (https://github.com/MovingBlocks/Terasology/pull/3917)
- [x] feat(JOML): Migrate BlockMeshLoader (https://github.com/MovingBlocks/Terasology/pull/3919)
- [x] feat(JOML): Migrate CharacterSoundSystem (https://github.com/MovingBlocks/Terasology/pull/3920)
- [x] feat(JOML): Migrate BlockEntityRegistry (https://github.com/MovingBlocks/Terasology/pull/3923)
- [x] feat(JOML): Migrate Material (https://github.com/MovingBlocks/Terasology/pull/3950)
- [x] feat(JOML) replace perspective and ortho with JOML impl (https://github.com/MovingBlocks/Terasology/pull/3948)
- [x] feat(JOML): Migrate RegionOutlineRenderer (https://github.com/MovingBlocks/Terasology/pull/4111)
- [x] backport changes from old bullet branch (https://github.com/MovingBlocks/Terasology/pull/4139)
- [x] feat(JOML): Migrate EntityPool (https://github.com/MovingBlocks/Terasology/pull/3965)
- [x] feat(JOML): BlockRegion replacement for Region3i (https://github.com/MovingBlocks/Terasology/pull/4011)
- [x] fix invisible skeletalmesh (https://github.com/MovingBlocks/Terasology/pull/4023)
- [x] feat(JOML): Migrate MeshRenderer (https://github.com/MovingBlocks/Terasology/pull/4026)
- [x] feat(JOML): Migrate EntityAwareWorldProviderTest (https://github.com/MovingBlocks/Terasology/pull/4030)
- [x] feat(JOML): Migrate BackdropProvider and Skysphere (https://github.com/MovingBlocks/Terasology/pull/4110)
- [x] feat(JOML): Migrate Tessellator (https://github.com/MovingBlocks/Terasology/pull/4084)
- [x] feat(JOML): Migrate PhysicsEngine#awakenArea (https://github.com/MovingBlocks/Terasology/pull/4083)
- [x] feat(JOML): migrate submersibleCamera (https://github.com/MovingBlocks/Terasology/pull/4070)
- [x] feat(JOML): Migrate Camera (https://github.com/MovingBlocks/Terasology/pull/4055)
- [x] feat(JOML): Migrate transpose Camera#getInverseProjectionMatrix() (https://github.com/MovingBlocks/Terasology/pull/4054)
- [x] feat(JOML): partial migrate of LocationComponent (https://github.com/MovingBlocks/Terasology/pull/4051)
- [x] feat(JOML): Migrate EntityAwareWorldProviderTest (https://github.com/MovingBlocks/Terasology/pull/4030)
- [x] feat(JOML): Migrate ChunkMath (https://github.com/MovingBlocks/Terasology/pull/4029)
- [x] feat(JOML): Correct matrix output for Camera#getProjectionMatrix() (https://github.com/MovingBlocks/Terasology/pull/4028)
- [x] feat(JOML): Migrate ViewFrustum (https://github.com/MovingBlocks/Terasology/pull/4027)
- [x] NUI Extraction JOML fix  (https://github.com/MovingBlocks/Terasology/pull/4020)
- [x] feat(JOML): migrate ChunkViewCore (https://github.com/MovingBlocks/Terasology/pull/3961)
- [x] feat(JOML) Migrate Side (https://github.com/MovingBlocks/Terasology/pull/3943)
- [x] feat(JOML): migrated Diamond3iIterator -> Diamond3iIterable (https://github.com/MovingBlocks/Terasology/pull/3935)
- [x] feat(JOML): Migrate PlayerSystem (https://github.com/MovingBlocks/Terasology/pull/3933)
- [x] https://github.com/Terasology/Genome/pull/20
- [x] https://github.com/Terasology/Inventory/pull/29
- [x] https://github.com/MovingBlocks/Terasology/pull/4344
- [x] https://github.com/MovingBlocks/Terasology/pull/4348
- [x] https://github.com/MovingBlocks/Terasology/pull/4346
- [x] https://github.com/MovingBlocks/Terasology/pull/4345
- [x] https://github.com/Terasology/Books/pull/32
- [x] https://github.com/Terasology/Breathing/pull/14
- [x] https://github.com/Terasology/ItemPipes/pull/26
- [x] https://github.com/Terasology/WoodAndStone/pull/67
- [x] https://github.com/Terasology/Alchemy/pull/15
- [x] https://github.com/MovingBlocks/Terasology/pull/4336
- [x] https://github.com/Terasology/Maze/pull/8
- [x] https://github.com/Terasology/Behaviors/pull/57
- [x] https://github.com/Terasology/MasterOfOreon/pull/87
- [x] https://github.com/Terasology/ItemRendering/pull/12

</details>

**Comment by pollend** [comment] 2020-03-25 02:49
here is a port of the skeleton renderer #3865

**Comment by pollend** [comment] 2020-03-25 05:23
here is a port for font vector2i #3866

**Comment by pollend** [comment] 2020-03-25 05:49
ported over skysphere to JOML also submersible camera. #3867

**Comment by pollend** [comment] 2020-03-27 15:06
here is another follow up PR that addresses serialization between JOML and termath. this should let prefabs have a mix of both termath and joml elements.: https://github.com/MovingBlocks/Terasology/pull/3869

**Comment by PS-Soundwave** [comment] 2020-04-06 06:31
Status on issues observed with #3811 ?

**Comment by Cervator** [comment] 2020-04-06 14:12
@PS-Soundwave the weird shadow/lighting quirk? I merged #3869 locally yesterday (then didn't get around to pushing it) and bumped to latest JOML. Issue still persisted - but then I'm not sure how recent it is. I checked an old workspace from December 2018 and didn't see it there.

**Comment by pollend** [comment] 2020-04-06 17:19
I've found problems by just running git bisect and finding the exact commit where it breaks. it could be a joml issue or something else. it should let you find the root cause of the problem.

**Comment by Cervator** [comment] 2020-04-07 03:32
Submitted #3881 with a detailed report on the lighting weirdness, it is related to the head bobbing effect and not present right before the big initial JOML PR.

**Comment by pollend** [comment] 2020-04-18 03:24
here is another PR but this one focuses on bullet. https://github.com/MovingBlocks/Terasology/pull/3894

**Comment by pollend** [comment] 2020-04-20 06:00
here is a PR that adds some joml swap in methods for some of the major systems in Terasology. https://github.com/MovingBlocks/Terasology/pull/3898

**Comment by jdrueckert** [comment] 2020-09-26 17:59
![](https://github.trello.services/images/mini-trello-icon.png) [Complete JOML](https://trello.com/c/hLnmMfiD/14-complete-joml)

**Comment by pollend** [comment] 2020-09-26 22:25
A pretty good portion of the codebase has been converted to JOML. 

Merged:
https://github.com/MovingBlocks/Terasology/pull/3833
https://github.com/MovingBlocks/Terasology/pull/3811
https://github.com/MovingBlocks/Terasology/pull/3866
https://github.com/MovingBlocks/Terasology/pull/3869
https://github.com/MovingBlocks/Terasology/pull/3885
https://github.com/MovingBlocks/Terasology/pull/3899
https://github.com/MovingBlocks/Terasology/pull/3902
https://github.com/MovingBlocks/Terasology/pull/3908
https://github.com/MovingBlocks/Terasology/pull/3912
https://github.com/MovingBlocks/Terasology/pull/3917
https://github.com/MovingBlocks/Terasology/pull/3919
https://github.com/MovingBlocks/Terasology/pull/3920
https://github.com/MovingBlocks/Terasology/pull/3923
https://github.com/MovingBlocks/Terasology/pull/3950
https://github.com/MovingBlocks/Terasology/pull/3948
https://github.com/MovingBlocks/Terasology/pull/4111
https://github.com/MovingBlocks/Terasology/pull/4139
https://github.com/MovingBlocks/Terasology/pull/3965
https://github.com/MovingBlocks/Terasology/pull/4011
https://github.com/MovingBlocks/Terasology/pull/4023
https://github.com/MovingBlocks/Terasology/pull/4026
https://github.com/MovingBlocks/Terasology/pull/4030
https://github.com/MovingBlocks/Terasology/pull/4110
https://github.com/MovingBlocks/Terasology/pull/4084
https://github.com/MovingBlocks/Terasology/pull/4083
https://github.com/MovingBlocks/Terasology/pull/4070
https://github.com/MovingBlocks/Terasology/pull/4055
https://github.com/MovingBlocks/Terasology/pull/4054
https://github.com/MovingBlocks/Terasology/pull/4051
https://github.com/MovingBlocks/Terasology/pull/4030
https://github.com/MovingBlocks/Terasology/pull/4029
https://github.com/MovingBlocks/Terasology/pull/4028
https://github.com/MovingBlocks/Terasology/pull/4028
https://github.com/MovingBlocks/Terasology/pull/4027
https://github.com/MovingBlocks/Terasology/pull/4026
https://github.com/MovingBlocks/Terasology/pull/4023
https://github.com/MovingBlocks/Terasology/pull/4020
https://github.com/MovingBlocks/Terasology/pull/4017
https://github.com/MovingBlocks/Terasology/pull/3961
https://github.com/MovingBlocks/Terasology/pull/3943
https://github.com/MovingBlocks/Terasology/pull/3935
https://github.com/MovingBlocks/Terasology/pull/3933

**Comment by pollend** [comment] 2020-09-26 22:40
A pretty good portion of the codebase has been converted to JOML.
Relevant PR:
- Expose JOML as a package to modules (https://github.com/MovingBlocks/Terasology/pull/3833)
- Feature/joml (https://github.com/MovingBlocks/Terasology/pull/3811)
- converted terasology vector2i to joml vector2i for font (https://github.com/MovingBlocks/Terasology/pull/3866)
- added serilization compatibility for joml along with a basic test for (https://github.com/MovingBlocks/Terasology/pull/3869)
- bumped version of joml and resolved direction of lightshafts (https://github.com/MovingBlocks/Terasology/pull/3885)
- feat(JOML): Migrate methods of WorldProvider (https://github.com/MovingBlocks/Terasology/pull/3899)
- partial port of kinematicCharacterMover (https://github.com/MovingBlocks/Terasology/pull/3902)
- JOML migration for AudioManager (https://github.com/MovingBlocks/Terasology/pull/3908)
- eat(JOML): Migrate PlayerFactory (https://github.com/MovingBlocks/Terasology/pull/3912)
- feat(JOML): Migrate Particle System (https://github.com/MovingBlocks/Terasology/pull/3917)
- feat(JOML): Migrate BlockMeshLoader (https://github.com/MovingBlocks/Terasology/pull/3919)
- feat(JOML): Migrate CharacterSoundSystem (https://github.com/MovingBlocks/Terasology/pull/3920)
- feat(JOML): Migrate BlockEntityRegistry (https://github.com/MovingBlocks/Terasology/pull/3923)
- feat(JOML): Migrate Material (https://github.com/MovingBlocks/Terasology/pull/3950)
- feat(JOML) replace perspective and ortho with JOML impl (https://github.com/MovingBlocks/Terasology/pull/3948)
- feat(JOML): Migrate RegionOutlineRenderer (https://github.com/MovingBlocks/Terasology/pull/4111)
- backport changes from old bullet branch (https://github.com/MovingBlocks/Terasology/pull/4139)
- feat(JOML): Migrate EntityPool (https://github.com/MovingBlocks/Terasology/pull/3965)
- feat(JOML): BlockRegion replacement for Region3i (https://github.com/MovingBlocks/Terasology/pull/4011)
- fix invisible skeletalmesh (https://github.com/MovingBlocks/Terasology/pull/4023)
- feat(JOML): Migrate MeshRenderer (https://github.com/MovingBlocks/Terasology/pull/4026)
- feat(JOML): Migrate EntityAwareWorldProviderTest (https://github.com/MovingBlocks/Terasology/pull/4030)
- feat(JOML): Migrate BackdropProvider and Skysphere (https://github.com/MovingBlocks/Terasology/pull/4110)
- feat(JOML): Migrate Tessellator (https://github.com/MovingBlocks/Terasology/pull/4084)
- feat(JOML): Migrate PhysicsEngine#awakenArea (https://github.com/MovingBlocks/Terasology/pull/4083)
- feat(JOML): migrate submersibleCamera (https://github.com/MovingBlocks/Terasology/pull/4070)
- feat(JOML): Migrate Camera (https://github.com/MovingBlocks/Terasology/pull/4055)
- feat(JOML): Migrate transpose Camera#getInverseProjectionMatrix() (https://github.com/MovingBlocks/Terasology/pull/4054)
- feat(JOML): partial migrate of LocationComponent (https://github.com/MovingBlocks/Terasology/pull/4051)
- feat(JOML): Migrate EntityAwareWorldProviderTest (https://github.com/MovingBlocks/Terasology/pull/4030)
- feat(JOML): Migrate ChunkMath (https://github.com/MovingBlocks/Terasology/pull/4029)
- feat(JOML): Correct matrix output for Camera#getProjectionMatrix() (https://github.com/MovingBlocks/Terasology/pull/4028)
- feat(JOML): Migrate ViewFrustum (https://github.com/MovingBlocks/Terasology/pull/4027)
- NUI Extraction JOML fix  (https://github.com/MovingBlocks/Terasology/pull/4020)
- feat(JOML): migrate ChunkViewCore (https://github.com/MovingBlocks/Terasology/pull/3961)
- feat(JOML) Migrate Side (https://github.com/MovingBlocks/Terasology/pull/3943)
- feat(JOML): migrated Diamond3iIterator -> Diamond3iIterable (https://github.com/MovingBlocks/Terasology/pull/3935)
- feat(JOML): Migrate PlayerSystem (https://github.com/MovingBlocks/Terasology/pull/3933)

**Comment by jdrueckert** [comment] 2020-09-27 11:34
Merged #4130

**Comment by jdrueckert** [comment] 2020-09-27 11:40
@pollend What about the following open PRs?

**Core:**
- #4159 
- #4124 
- #4072 
- #4050 
- #4069 
- #3945 

**Modules:**
- https://github.com/Terasology/AdvancedRails/pull/5
- https://github.com/Terasology/Alchemy/pull/9
- https://github.com/Terasology/Inventory/pull/6
- https://github.com/Terasology/KComputers/pull/1
- https://github.com/Terasology/Rails/pull/51
- https://github.com/Terasology/AdditionalRails/pull/36
- https://github.com/Terasology/ComputerMonitors/pull/1
- https://github.com/Terasology/Lakes/issues/7

Please be so kind and update the _description_ of this PR to list _all_ PRs outstanding to call JOML "complete", their status [WIP|RFR(ready-for-review)] and their complexity.

**Comment by pollend** [comment] 2020-10-02 20:35
there seems to be some problems with rails related to PR: https://github.com/MovingBlocks/Terasology/pull/4069

https://github.com/Terasology/Rails

**Comment by pollend** [comment] 2020-12-29 02:52
- [ ] https://github.com/Terasology/Minesweeper/pull/19
- [ ] https://github.com/Terasology/Genome/pull/20
- [ ] https://github.com/Terasology/Inventory/pull/29
- [ ] https://github.com/Terasology/WeatherManager/pull/18
- [ ] https://github.com/MovingBlocks/Terasology/pull/4344
- [ ] https://github.com/MovingBlocks/Terasology/pull/4348
- [ ] https://github.com/MovingBlocks/Terasology/pull/4346
- [ ] https://github.com/MovingBlocks/Terasology/pull/4345
- [ ] https://github.com/Terasology/Books/pull/32
- [ ] https://github.com/Terasology/LightAndShadow/pull/181
- [ ] https://github.com/Terasology/Breathing/pull/14
- [ ] https://github.com/Terasology/ItemPipes/pull/26
- [ ] https://github.com/Terasology/WoodAndStone/pull/67
- [ ] https://github.com/Terasology/Alchemy/pull/15

**Comment by skaldarnar** [comment] 2020-12-31 14:43
Sorted the todo list into **Backlog** and **Done** (and hide the done items in a `<details>...` tag).

**Comment by skaldarnar** [comment] 2021-02-25 22:22
:partying_face: :confetti_ball: :champagne:

**Closed by skaldarnar** 2021-02-25 22:22 UTC
Labels: Architecture, Bug, Performance, Rendering, Research
