### ISSUE TITLE
ExceptionInInitializerError (NoClassDefFoundError) during Advanced Game Setup (AGS)

### ISSUE THREAD

**Issue by KdotJPG** [MovingBlocks/Terasology#4801] opened 2021-06-28 06:24 UTC
### What you were trying to do

Create a custom world/universe type to further test some changes.

### What actually happened

Crashes when I click Configure or Continue to Pregeneration

### How to reproduce

* Choose 'Single Player' on the main screen
* Click the 'Create' button
* Click 'Advanced'
* Try any configuration of modules (I've tried with all disabled and all enabled except for Module Testing Environment)
* Click 'Continue to Universe Setup'
* Choose a world generator and click 'Add', 
* Click 'Configure'
  * Alternatively, click 'Continue to Pregeneration'

![image](https://user-images.githubusercontent.com/8829856/123589779-b6281800-d7b7-11eb-8ac5-dab401e1b43a.png)

### Game version

ALPHA-20 from the `develop` branch (latest commit was [#fbeed19](https://github.com/MovingBlocks/Terasology/commit/fbeed19316403e76a88bb2da85f89f0bad2e1e48)) and run with `gradlew game`

### Log details

```
02:22:03.165 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
02:22:03.169 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
02:22:03.169 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
02:22:03.341 [main] WARN  o.t.engine.registry.InjectionHelper - CoreCommands wanted BlockManager injected but CoreRegistry has none.
02:22:03.354 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted WorldProvider injected but CoreRegistry has none.
02:22:03.354 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted DelayManager injected but CoreRegistry has none.
02:22:03.354 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted PhysicsEngine injected but CoreRegistry has none.
02:22:03.355 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
02:22:03.355 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
02:22:03.355 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
02:22:04.124 [main] WARN  org.terasology.nui.WidgetUtil - Contents of org.terasology.engine.rendering.nui.layers.mainMenu.MainMenuScreen@52d434c1 missing button with id 'storageServiceAction'
02:22:04.179 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (5474), capping to 1000
02:23:02.873 [main] WARN  o.t.e.r.n.layers.mainMenu.WaitPopup - An error occurred during execution
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WaitPopup.update(WaitPopup.java:87)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:592)
	at org.terasology.engine.core.modes.StateMainMenu.updateUserInterface(StateMainMenu.java:228)
	at org.terasology.engine.core.modes.StateMainMenu.update(StateMainMenu.java:200)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:504)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:464)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
Caused by: java.lang.ExceptionInInitializerError: null
	at org.terasology.core.world.generator.facetProviders.DefaultFloraProvider.<init>(DefaultFloraProvider.java:63)
	at org.terasology.core.world.generator.worldGenerators.SimplexFacetedWorldGenerator.createWorld(SimplexFacetedWorldGenerator.java:68)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.setWorldSeed(BaseFacetedWorldGenerator.java:45)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setWorldGenerators(WorldPreGenerationScreen.java:291)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setEnvironment(WorldPreGenerationScreen.java:88)
	at org.terasology.engine.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$4(UniverseSetupScreen.java:213)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at org.terasology.core.world.CoreBiome.<init>(CoreBiome.java:48)
	at org.terasology.core.world.CoreBiome.<clinit>(CoreBiome.java:26)
	... 9 common frames omitted
02:23:18.268 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoClassDefFoundError: Could not initialize class org.terasology.core.world.CoreBiome
	at org.terasology.core.world.generator.facetProviders.DefaultFloraProvider.<init>(DefaultFloraProvider.java:63)
	at org.terasology.core.world.generator.worldGenerators.SimplexFacetedWorldGenerator.createWorld(SimplexFacetedWorldGenerator.java:68)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getConfigurator(BaseFacetedWorldGenerator.java:74)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.configureProperties(WorldSetupScreen.java:162)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.setWorld(WorldSetupScreen.java:146)
	at org.terasology.engine.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$1(UniverseSetupScreen.java:173)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
	at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:680)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:254)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:233)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
	at org.terasology.engine.input.InputSystem.send(InputSystem.java:524)
	at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:496)
	at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
	at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
	at org.terasology.engine.core.modes.StateMainMenu.handleInput(StateMainMenu.java:195)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:513)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:464)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
02:23:18.268 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...
```

```
02:05:57.624 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
02:05:57.627 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
02:05:57.628 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
02:05:57.787 [main] WARN  o.t.engine.registry.InjectionHelper - CoreCommands wanted BlockManager injected but CoreRegistry has none.
02:05:57.799 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted WorldProvider injected but CoreRegistry has none.
02:05:57.799 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted DelayManager injected but CoreRegistry has none.
02:05:57.800 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted PhysicsEngine injected but CoreRegistry has none.
02:05:57.800 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
02:05:57.800 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
02:05:57.800 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
02:05:58.515 [main] WARN  org.terasology.nui.WidgetUtil - Contents of org.terasology.engine.rendering.nui.layers.mainMenu.MainMenuScreen@52d434c1 missing button with id 'storageServiceAction'
02:05:58.525 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (5602), capping to 1000
02:07:12.647 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ExceptionInInitializerError: null
	at org.terasology.core.world.generator.facetProviders.DefaultFloraProvider.<init>(DefaultFloraProvider.java:63)
	at org.terasology.core.world.generator.worldGenerators.PerlinFacetedWorldGenerator.createWorld(PerlinFacetedWorldGenerator.java:70)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getConfigurator(BaseFacetedWorldGenerator.java:74)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.configureProperties(WorldSetupScreen.java:162)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.setWorld(WorldSetupScreen.java:146)
	at org.terasology.engine.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$1(UniverseSetupScreen.java:173)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
	at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:680)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:254)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:233)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
	at org.terasology.engine.input.InputSystem.send(InputSystem.java:524)
	at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:496)
	at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
	at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
	at org.terasology.engine.core.modes.StateMainMenu.handleInput(StateMainMenu.java:195)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:513)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:464)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
Caused by: java.lang.NullPointerException: null
	at org.terasology.core.world.CoreBiome.<init>(CoreBiome.java:48)
	at org.terasology.core.world.CoreBiome.<clinit>(CoreBiome.java:26)
	... 33 common frames omitted
02:07:12.649 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...
```

**Comment by jdrueckert** [comment] 2021-06-28 06:43
Hi @KdotJPG thanks for the report.
Terasology is not expected to run with either no modules or all modules.

The module combination selected by the "CoreGameplay" preset is the minimum combination of modules you'll need to start a world. Granted - we should add some safe-guards in the Advanced Game Setup (AGS) to make sure, these are enabled.

Enabling all modules will also not work as some modules just won't work together - which I thought we actually indicate in the AGS 🤔 Also, I think there's currently 3-4 modules that have a bug and might crash the game on start when selected. Granted - we should make these regressions more visible somehow.

In addition, building from develop can always have some issues which we try to find and fix for the next release.

**Comment by KdotJPG** [comment] 2021-06-28 07:02
Fair enough! Wanted to make sure I submitted any appropriate bug reports given that I mentioned this bug in a PR as coming up during testing.

I suppose the main bug report here then, is that the crash itself occurs, rather than any particular options not working.

If it's worth mentioning, I am seeing a similar error with the following modules selected to match the selected modules to the dependencies listed under the Core Gameplay module.
![image](https://user-images.githubusercontent.com/8829856/123593151-305a9b80-d7bc-11eb-8725-c9daa1602728.png)

The same thing happens when I have no modules selected, with the exception of Core Gameplay which is what I had tested originally. Related clarification: I only selected all of the modules available under the 'Local' filter, not all of the modules total.

Additionally, when I click 'Continue to Pregeneration' it fails gracefully and lets me click OK to return to what I was doing. If I click 'Configure', that is when the entire game crashes.
![image](https://user-images.githubusercontent.com/8829856/123593413-79aaeb00-d7bc-11eb-94d2-cc1887e4278a.png)
![image](https://user-images.githubusercontent.com/8829856/123594050-3735de00-d7bd-11eb-97f4-5624ee91aecd.png)

**Comment by pollend** [comment] 2021-06-28 14:15
@KdotJPG the advanced world generation is one of the more weaker portions of the codebase. there is configurations to have multiple worlds but was never fully implemented or worked out. probably need to spend time to investigate this more at some point in the future. great to see some clear steps on reproducing this.

**Comment by jdrueckert** [comment] 2021-06-28 14:58
@KdotJPG Thanks a lot for the additional information!

General question: Is your workspace up to date (both, engine and all module repos, on latest commit of `develop`)?

> If it's worth mentioning, I am seeing a similar error with the following modules selected to match the dependencies listed under the Core Gameplay module.

That should definitely not happen. That selection in the screenshot seems valid and should result in the same as if you would directly start Core Gameplay without going through the AGS... 

> The same thing happens when I have no modules selected, with the exception of Core Gameplay [...]

Theoretically, it should not easily be feasible to disable modules another module requires, so if you enable Core Gameplay it's dependencies should be enabled too 🤔 

> When I tested 'all modules', I only selected all of the modules available under the 'Local' filter, not all of the modules entirely.

Which ones did you have locally available? Did you `./gradlew module init iota` or `./gradlew module init omega` or did you only `./gradlew module [get | recurse]` specific modules?

> Additionally, when I click 'Continue to Pregeneration' it fails gracefully and lets me click OK to return to what I was doing. If I click 'Configure', that is when the entire game crashes.

Okay, then we might miss some check on that path, thanks for the hint 👍

**Comment by KdotJPG** [comment] 2021-07-02 05:18
> General question: Is your workspace up to date (both, engine and all module repos, on latest commit of `develop`)?

It was on the latest commit at the time, yes. [#fbeed19](https://github.com/MovingBlocks/Terasology/commit/fbeed19316403e76a88bb2da85f89f0bad2e1e48)

> Which ones did you have locally available? Did you `./gradlew module init iota` or `./gradlew module init omega` or did you only `./gradlew module [get | recurse]` specific modules?

I believe I did iota, when following the quick-start guide linked in the readme. Running it now to make sure, I get messages that indicate the module directories already exist, and the modules shown on the advanced screen are the same as before. I also still get the initializer error. Now doing omega, I see the longer list of modules, but get the same error when doing what I was doing before.

> Okay, then we might miss some check on that path, thanks for the hint 👍

Glad to help!

**Comment by tolziplohu** [comment] 2021-07-02 16:09
I'm pretty sure this is the same issue that I noticed yesterday, caused by https://github.com/Terasology/CoreWorlds/pull/35. `CoreBiome`'s initialiser tries to get some blocks from the `BlockManager`, but the blocks haven't been registered yet, so it crashes. So either we need to register blocks earlier, or do that part of biome initialization later.

**Comment by jdrueckert** [comment] 2021-07-03 17:54
> I'm pretty sure this is the same issue that I noticed yesterday, caused by [Terasology/CoreWorlds#35](https://github.com/Terasology/CoreWorlds/pull/35). `CoreBiome`'s initialiser tries to get some blocks from the `BlockManager`, but the blocks haven't been registered yet, so it crashes. So either we need to register blocks earlier, or do that part of biome initialization later.

As mentioned on [Discord](https://discord.com/channels/270264625419911192/702893102481932308/860901735156416543), I rather think this is due to the `BlockManager` not being present in `CoreRegistry` at that point in time yet.

I'll create another issue regarding
> Additionally, when I click 'Continue to Pregeneration' it fails gracefully and lets me click OK to return to what I was doing. If I click 'Configure', that is when the entire game crashes.

as this is a separate problem that I assume we face irrespective of whatever bug we're failing with. Clicking on 'Configure' should ideally result in the same graceful failures as clicking on 'Continue to Pregeneration' does.

**Comment by skaldarnar** [comment] 2021-07-09 17:32
Fixed by https://github.com/Terasology/BiomesAPI/pull/16, https://github.com/Terasology/CoreWorlds/pull/39 and related changes.

**Closed by skaldarnar** 2021-07-09 17:32 UTC
Labels: Category: Crash, Topic: WorldGen, Type: Bug
