### ISSUE TITLE
Crash on ARM plateform

### ISSUE THREAD

**Issue by niansa** [MovingBlocks/Terasology#3412] opened 2018-06-30 12:46 UTC
### What you were trying to do

I tried to start the game.

### What actually happened

The game closed during start and a crash-reporter appeared

### How to reproduce

* Start the game
* Wait some time

### Log details and game version

https://pastebin.com/4gma9XTU

### Computer details

Rasberry Pi 3 (Ubuntu Mate)

**Comment by jellysnake** [comment] 2018-07-01 02:39
That log looks a little short. How far into loading the game did you get?
Additionally are you running the game as a server or regularly? (I only ask because I noticed the hardware you've listed is a Pi)

**Comment by Cervator** [comment] 2018-07-15 03:49
Closing from lack of info / follow-up. I'm not really sure we're Pi compatible yet :-)

@niansa if you have more information available feel free to reopen. Otherwise here's for hoping you can find other systems to run the game on!

**Closed by Cervator** 2018-07-15 03:49 UTC
Labels: Bug, Needs Info

**Comment by theobisproject** [comment] 2019-05-26 09:48
I tried this for fun.

**Running regularly**
Command used: `gradlew game`
The game crashes after the splashscreen. The logfile does not provide any useful information but the crash reporter screen does. The problem is the `liblwjgl.so` binary which is compiled for the x86 architecture and not for arm. Error message is: `can't load IA 32-bit .so on a ARM-bit platform`.
There are some ways to get LWJGL2 to work on an Raspberry Pi but nothing which could be easily integrated (e.g. [for Minecraft](https://www.raspberrypi.org/forums/viewtopic.php?t=186547)).
LWJGL3 does not have precompiled binaries yet. But they are working to support the Raspberry Pi.

**Running headless server**
Command used: `gradlew server`
This works quite nice. The server starts and players can join.
My Raspberry server crashed about 10 seconds after joining it. This might be due to the limited amount of memory the process got (I didn't looked at it further and the Gradle Exception is not helpful at all).

**Comment by Adriankhl** [comment] 2021-01-19 06:23
I think LWJGL3 now has arm support https://github.com/LWJGL/lwjgl3/issues/206

My problem is that JNBullet (https://github.com/MovingBlocks/JNBullet) doesn't have arm build. I guess that shouldn't be too difficult?

**Comment by DarkWeird** [comment] 2021-01-19 07:29
> I think LWJGL3 now has arm support [LWJGL/lwjgl3#206](https://github.com/LWJGL/lwjgl3/issues/206)
> 
> My problem is that JNBullet (https://github.com/MovingBlocks/JNBullet) doesn't have arm build. I guess that shouldn't be too difficult?

Terasology haven't arm support too. (arm natives for lwjgl not fetching)
which Operation system?

**Comment by Adriankhl** [comment] 2021-01-19 07:57
> which Operation system?

Raspberry pi OS 64 bit, which is basically debian arm64. At least I am able to run some libgdx games which use lwjgl3 as the backend. So in principle terasology can do it, given that the dependent native libraries can be compiled for arm linux. Though I should admit that I don't understand how lwjgl3 works, maybe it takes more effort to make this player on raspberry pi.

**Comment by DarkWeird** [comment] 2021-01-19 08:10
> > which Operation system?
> 
> Raspberry pi OS 64 bit, which is basically debian arm64. At least I am able to run some libgdx games which use lwjgl3 as the backend. So in principle terasology can do it, given that the dependent native libraries can be compiled for arm linux. Though I should admit that I don't understand how lwjgl3 works, maybe it takes more effort to make this player on raspberry pi.

Yeah.
I looked at lwjgl3 and our code.
Just needs to add arm64 distribution with fetching arm64 platform.

I looked at bullet3 also.
There more complex problem:
bullet3 supports arm64, but it made for NVIDA TX2 (https://github.com/bulletphysics/bullet3/pull/1030/commits)
we use our wrapper for bullet3, which building with gradle and dist as zip.
There needs to add new cmake and gradle target and release arm64 version.

**Comment by skaldarnar** [comment] 2021-01-19 11:14
Let's take this to a new discussion and not post in this closed bug report issue: https://github.com/MovingBlocks/Terasology/discussions/4416
