### ISSUE TITLE
Block scrambling - something causes blocks to change shape/texture and function

### ISSUE THREAD

**Issue by Taose** [MovingBlocks/Terasology#2622] opened 2016-11-23 01:52 UTC
### What you were trying to do
Play.

### What actually happened
Blocks became different shapes... 

### How to reproduce

I can't replicate it reliably and I have no idea what's causing it, but it happens often about every ten hours of gameplay or so. I've booted numerous worlds and it's not always shapes that cause it. Sometimes hitting the wrong thing can cause the scramble...and it usually affects torches but not always. 

* Step 1
Get into game and do some building. A mine perhaps, spend a few hours. 

* Step 2
Start getting some shapes of stone blocks and using them.

* Step 3
Eventually other items will start changing into stone block shapes or something else will scramble. 

### Log details and game version

[Terasology-init (copy).txt](https://github.com/MovingBlocks/Terasology/files/607975/Terasology-init.copy.txt)
[Terasology-menu (copy).txt](https://github.com/MovingBlocks/Terasology/files/607977/Terasology-menu.copy.txt)
[Terasology-Nasuaa (copy).txt](https://github.com/MovingBlocks/Terasology/files/607978/Terasology-Nasuaa.copy.txt)

### Computer details

It's probably not a computer problem, and I've submitted my computer details in a few other issues. 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39470767-scrambling?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).

**Comment by portokaliu** [comment] 2016-11-23 09:25
I can confirm this happens. Did get the issue a couple of times while trying to get a module going. The blocks that change don't just have the shape or texture changed, but their function as well (had blocks of lava turned into ladders, and climbing them was possible. Placing lava blocks after it happened was just placing ladders.

**Comment by Cervator** [comment] 2016-11-24 06:22
Thanks for getting an issue on this started @Feralmouse 

> The blocks that change don't just have the shape or texture changed, but their function as well

Now that's interesting. IIRC past issues like this have been purely texture related (scrambled block tile atlas / interactions somehow?) - I have seen the sea turn into all TNT, but none of it would `e` click. Same with stuff turning into torches which murdered the framerate but didn't affect lighting. Both of those were long ago though.

**Comment by SoniEx2** [comment] 2016-12-29 16:08
Where are block IDs handled?

**Comment by DPirate** [comment] 2017-03-24 13:53
I had torches turning into oak wood(still produced light) when i placed them against the face of any block which was in a particular direction. Could not reproduce it in any other world, but that world still does it. I had several modules enabled.

**Comment by Cervator** [comment] 2017-03-26 17:15
Closing this as likely fixed via #2861! Hooray :-)

**Closed by Cervator** 2017-03-26 17:15 UTC
Labels: Bug
