### ISSUE TITLE
Lower Resolution Scaling Problem (1024x768)

### ISSUE THREAD

**Issue by arpitkamboj** [MovingBlocks/Terasology#2716] opened 2016-12-28 16:32 UTC
I found some screens having scaling problems in a lower resolution (1024x768)

![screenshot 86](https://cloud.githubusercontent.com/assets/16421831/21526123/e04e3026-cd47-11e6-84d6-4018338fdaef.png)
createGameScreen.ui

![screenshot 84](https://cloud.githubusercontent.com/assets/16421831/21526218/88325e0c-cd48-11e6-981a-9a126271d8ea.png)
migTestScreen.ui
(Many Problems)

![screenshot 87](https://cloud.githubusercontent.com/assets/16421831/21540729/431fe3cc-cdd7-11e6-89c2-87abde792bcb.png)

![screenshot 88](https://cloud.githubusercontent.com/assets/16421831/21540730/43201194-cdd7-11e6-980b-65eab1fe6c4f.png)
In NUI Editor and NUI Skin Editor, when editing 'behaviorEditorScreen'.

**Comment by smsunarto** [comment] 2016-12-29 17:57
The first problem has already been solved #2638 
The third one is a duplicate #2655

**Comment by TheOddDolphin** [comment] 2017-01-18 16:28
I'm unsure that this issue has in fact been fixed. My workspace is fully up-to-date, and still I get:
![terasologybug1](https://cloud.githubusercontent.com/assets/24751163/22072206/99ade4b4-ddc7-11e6-8e33-39dd376a6171.jpg)

I've narrowed the bug down a bit, so although I'm not really sure where it is in the code, I can with confidence say that it is due to the margin between the bottom of the window and the last row of buttons taking precedence over the actual layout of the menu, whether it is a window like the above, or a window resized down, like so:

![terasologybug1](https://cloud.githubusercontent.com/assets/24751163/22072432/64f08712-ddc8-11e6-82d5-a1faebdbae5e.jpg)

As you can see, the bottom margin is preserved at a minimum value no matter what the size of the window is.

**Comment by smsunarto** [comment] 2017-01-18 23:07
@TheOddDolphin Yes, for some gameplay template that do have long text this problem still persist. But the  first picture in the issue belongs from an old version which have a "Save Game Path" section which actually pushes down the screen even more.

**Comment by TheOddDolphin** [comment] 2017-02-17 18:47
@smsunarto Sorry about the delay in my reply, but I just managed to update my own fork and corresponding local clone to check if the problem still persists and unfortunately it does. Issue #2585 has a probable solution, but the thread seems to be stale, last updated in November last year.

**Comment by TheOddDolphin** [comment] 2017-02-28 15:46
Just wanted to let you guys know that I'm going to be taking a look at this issue. Hopefully, I'll be able to come up with a satisfactory solution.

**Comment by jellysnake** [comment] 2018-01-29 07:56
Further discussion happened on #3182. Check there if intending to create a fix

**Comment by skaldarnar** [comment] 2023-07-02 16:52
Duplicate of #2585.

**Closed by skaldarnar** 2023-07-02 16:52 UTC
