### ISSUE TITLE
Game crashes with Master of Oreon

### ISSUE THREAD

**Issue by fluffynuts** [MovingBlocks/Terasology#3694] opened 2019-06-23 15:59 UTC
This is the first time I'm trying to run the game, so I'm not sure if I'm just doing something wrong -- tried to start up a new game with the type "master of {something}". The crash reporter offered to file a GitHub issue, but clicking that button didn't do anything, so I'm reporting manually in case it's something of interest.

log file here: https://pastebin.com/417RDRky

OS: Linux (Gentoo)

**Comment by Cervator** [comment] 2019-06-29 17:25
Update: two others were unable to reproduce and after cleaning up my local source workspace I couldn't either. I rebuilt some associated modules and made sure there was a new game zip for the launcher, tested it out there as well and it worked :-)

@fluffynuts could you try again please? Either latest develop build via launcher or http://jenkins.terasology.org/job/DistroOmega/1040/artifact/distros/omega/build/distributions/TerasologyOmega.zip

Going to close this as hopefully resolved :-)

**Closed by Cervator** 2019-06-29 17:25 UTC
Labels: Blocker, Bug, Content
