### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheNoim** [MovingBlocks/Terasology#1811] opened 2015-07-04 21:11 UTC
https://docs.google.com/uc?id=0B5l2RT_UOCXRRHVRWWF0LUVuS3M&export=download

**Comment by Cervator** [comment] 2015-07-05 03:33
Hi @TheNoim - we need some more information than that. What were you trying to do? What gameplay/modules did you go with? What build did you download? And so on.

The CrashReporter should show all the relevant logs, not just the error message (there should be multiple tabs to look at). The more logs we have access to the better :-)

**Comment by immortius** [comment] 2015-07-07 08:44
Well, ```org.terasology.was.generator.plant.forest.tree.CypressForestSpawnDefinition``` didn't load I guess. I don't know in what context (previewing a world, loading a game, starting a new game) - that would be helpful. I don't know if the module that holds that class has changed recently either.

**Comment by Cervator** [comment] 2015-07-10 03:07
I just tried out Throughout the Ages in develop (Cypress lives in the WoodAndStone module, part of TTA) and it worked. Preview half-works then crashes, but for other reasons.

I'm going to expect either an issue in an older build we've since fixed or something more quirky we cannot reproduce without more info.

Closing as resolved/unresolvable unless more info shows up - @TheNoim feel free to re-open if you can get us more log files :-)

**Closed by Cervator** 2015-07-10 03:07 UTC
Labels: Support
