### ISSUE TITLE
Fence floats when block below it is destroyed

### ISSUE THREAD

**Issue by ebackhaus** [MovingBlocks/Terasology#3557] opened 2018-11-26 04:53 UTC
### What you were trying to do
Destroy block below fence, assumed fence would be destroyed too

### What actually happened
Block below fence is destroyed, but fence floats

### How to reproduce

* Place fence
* Destroy block below fence

![fence floats when block below it is destroyed](https://user-images.githubusercontent.com/42822402/48992565-f99ce000-f0fd-11e8-9b08-e3dea481bd40.gif)

### Log details and game version
v2.1.0 - Alpha 11

### Computer details
Windows 10 64-bit
RAM 12 GB

**Comment by Alohacajun** [comment] 2018-11-26 15:30
I don't believe this is a bug, I actually use floating fences in my builds sometimes :P

**Comment by jellysnake** [comment] 2018-11-27 01:05
Thanks for the testing :) Seen your issues around on a number of modules lately.
This one isn't actually a bug, rather it's intended behaviour, so I'm going to mark this as such and close it.

If this type of behaviour is something that interests you then it could be implemented through a module. You could even go further and disallow all floating blocks if you wanted or even implement a pseudo-gravity where a block has to have a constant connection to the ground

**Closed by jellysnake** 2018-11-27 01:05 UTC
