### ISSUE TITLE
Crash Report - Linux Mint 18.1 [AMD/ATI]

### ISSUE THREAD

**Issue by HackerControHacker** [MovingBlocks/Terasology#3081] opened 2017-08-26 09:16 UTC
### logs info

11:10:25.254 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
11:10:25.359 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=, buildId=, buildTag=, buildUrl=, gitBranch=, gitCommit=, dateTime=, displayVersion=, engineVersion=]
11:10:25.359 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: /home/linux/.local/share/terasology
11:10:25.363 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: /usr/share/games/terasology
11:10:25.364 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 1.8.0 in /usr/lib/jvm/java-ibm-x86_64-80/jre
11:10:25.364 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: IBM J9 VM, version: 2.8
11:10:25.364 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Linux, arch: amd64, version: 4.4.0-92-generic
11:10:25.365 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 1024 MiB
11:10:25.365 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 4
11:10:26.935 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.lang.RuntimeException: Unexpected exception generating certificate
	at org.terasology.identity.CertificateGenerator.generateSelfSigned(CertificateGenerator.java:78)
	at org.terasology.engine.subsystem.common.ConfigurationSubsystem.checkServerIdentity(ConfigurationSubsystem.java:71)
	at org.terasology.engine.subsystem.common.ConfigurationSubsystem.preInitialise(ConfigurationSubsystem.java:61)
	at org.terasology.engine.TerasologyEngine.preInitSubsystems(TerasologyEngine.java:243)
	at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:181)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:361)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
Caused by: java.security.spec.InvalidKeySpecException: Inappropriate key specification
	at com.ibm.crypto.provider.RSAKeyFactory.engineGetKeySpec(Unknown Source)
	at java.security.KeyFactory.getKeySpec(KeyFactory.java:432)
	at org.terasology.identity.CertificateGenerator.generateSelfSigned(CertificateGenerator.java:65)
	... 6 common frames omitted
11:10:26.936 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...

### Computer details

Linux Mint 18.1

Kernel Linux: 4.4.0-92-generic

Advaced Micro Devices, Inc. [AMD/ATI] Carrizo

**Comment by gianluca-nitti** [comment] 2017-08-28 10:25
I think it's related to the JVM you are using (IBM J9 VM), looks like it isn't able to generate the RSA keys necessary for the client-server authentication protocol (IIRC, even if you aren't using multiplayer, at startup the game initializes the keys to be used if you want to host a server).

I'd suggest you use openjdk (or Oracle jvm if it's still available in your distribution).

**Comment by jellysnake** [comment] 2018-01-30 04:28
As gianluca-nitti said, this issue is caused by using Java 9. We currently use Java 8 and don't support 9. 
I'm closing this as solved but please reopen if changing java version doesn't solve it

**Closed by jellysnake** 2018-01-30 04:28 UTC
