### ISSUE TITLE
Terasology fails to create home directory for headless server

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/Terasology#4957] opened 2021-11-20 13:48 UTC
### What you were trying to do

Start a headless server
```bash
./gradlew server
```

### What actually happened

Headless server failed to start

### How to reproduce

1. Run `./gradlew server` and notice that it fails to start with below-mentioned logs
1. Create directory (e.g. `mkdir terasology-server` in workspace root dir)
1. Re-run `./gradlew server` and notice that the server starts successfully

### Log details

```
> Task :facades:PC:server
14:44:20.448 [main] INFO  org.terasology.engine.Terasology - homeDir is terasology-server
PathManager: Initial code location is /home/<user>/Terasology-mr/engine/build/libs/engine-5.2.0-SNAPSHOT.jar
PathManager: Working directory is /home/<user>/Development/Git/Terasology-mr
java.nio.file.NoSuchFileException: terasology-server
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:860)
        at org.terasology.engine.core.PathManager.useOverrideHomePath(PathManager.java:165)
        at org.terasology.engine.Terasology.handleLaunchArguments(Terasology.java:243)
        at org.terasology.engine.Terasology.call(Terasology.java:143)
        at org.terasology.engine.Terasology.call(Terasology.java:69)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.terasology.engine.Terasology.main(Terasology.java:138)
```

### Workaround

Create home directory before attempting to start the server
```
mkdir terasology-server
```

**Comment by keturn** [comment] 2021-11-20 17:39
Duplicate of #4917

**Closed by keturn** 2021-11-20 17:39 UTC
Labels: Type: Bug, Status: Needs Investigation, Topic: UI/UX, Size: S, Category: Crash

**Comment by jdrueckert** [comment] 2021-11-20 18:29
![](https://github.trello.services/images/mini-trello-icon.png) [Discuss: Should the homedir created if it's not present yet?](https://trello.com/c/wXYEjUbm/210-discuss-should-the-homedir-created-if-its-not-present-yet)
